// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_ko.js
// ---------------------------------------------------------------------------------------------------------------------
// WARNING: Computer generated file.  Do not hand modify.
// DEPENDS ON: ['scriptsharp/src/Resources/Strings/Strings.en.resx', 'scriptsharp/src/Resources/Strings/Strings.ko.resx', 'scriptsharp/src/Resources/Strings/resx-strings-js.template']

(function(w) {
  var s = {
    AODialogBandTabTitle: "구간",
    AODialogCellScope: "셀",
    AODialogComputationLabel: "계산",
    AODialogCustomLabelLabel: "사용자 지정 레이블",
    AODialogCustomTooltipLabel: "사용자 지정 도구 설명",
    AODialogDistributionTabTitle: "분포",
    AODialogFactorsLabel: "요소",
    AODialogFromValueLabel: "값(이전)",
    AODialogInstantAnalyticsBandLabel: "선택된 데이터의 구간 다시 계산",
    AODialogInstantAnalyticsLineLabel: "선택된 데이터의 라인 다시 계산",
    AODialogLabelLabel: "레이블",
    AODialogLineTabTitle: "라인",
    AODialogNumberOfTilesLabel: "타일 수",
    AODialogPaneScope: "패널",
    AODialogPercentOfLabel: "비율",
    AODialogPercentagesLabel: "백분율",
    AODialogPercentilesLabel: "백분위수",
    AODialogQuantiles: "사분위수",
    AODialogStandardDeviation: "표준 편차",
    AODialogTableScope: "테이블",
    AODialogTitleString: "{0} 편집",
    AODialogToValueLabel: "값(이후)",
    AODialogTooltipLabel: "도구 설명",
    AODialogValueLabel: "값",
    AccelerationButtonText: "가속화",
    AccelerationCurrentState_AccelerationUnavailable: "가속 사용 불가능",
    AccelerationCurrentState_Enabled: "뷰 가속화",
    AccelerationCurrentState_Failed: "가속 실패",
    AccelerationCurrentState_Pending: "가속 보류 중",
    AccelerationDialogDescription: "오랫동안 실행되는 쿼리가 뷰에 있는 경우 가속은 뷰의 초기 로드 시간을 줄여줍니다.",
    AccelerationDialogStateError: "대화 상자에서 가속 단계를 변경할 수 없음",
    AccelerationDialogTitle: "뷰 가속화",
    AccelerationDisallowed: "가속 사용 불가능",
    AccelerationDisallowedReason_AccelerationFutile: "가속은 이 뷰의 성능을 크게 향상시키지 않습니다.",
    AccelerationDisallowedReason_AccelerationFutileNull: "이 뷰에는 가속을 아직 사용할 수 없습니다. 나중에 다시 확인하십시오.",
    AccelerationDisallowedReason_AdminDisallowed: "이 뷰에 대한 가속이 일시 중단되었습니다. 관리자에게 문의하십시오.",
    AccelerationDisallowedReason_CredentialsNotEmbedded: "이 뷰는 자격 증명이 내장되어 있지 않으므로 가속화할 수 없습니다.",
    AccelerationDisallowedReason_EncryptedExtract: "이 뷰는 암호화된 데이터 원본 추출을 사용하므로 가속화할 수 없습니다.",
    AccelerationDisallowedReason_SheetLimitHit: "이 사이트에서 가속화할 수 있는 뷰 수 제한에 도달했습니다. 관리자에게 문의하십시오.",
    AccelerationDisallowedReason_UnsupportedDataFreshnessPolicy: "데이터 새로 고침 정책이 4시간 미만이므로 이 뷰를 가속화할 수 없습니다. 데이터 새로 고침 정책을 편집하십시오.",
    AccelerationDisallowedReason_UnsupportedDataFreshnessPolicyWithConfig: "데이터 새로 고침 정책이 {0}시간 미만이므로 이 뷰를 가속화할 수 없습니다. 데이터 새로 고침 정책을 편집하십시오.",
    AccelerationDisallowedReason_UnsupportedDatasourceType: "가속으로 지원되지 않는 데이터 원본이 통합 문서에 사용됩니다.",
    AccelerationDisallowedTooltip: "이 뷰를 가속화할 수 없습니다. 이유: {0}",
    AccelerationError: "오류가 발생했습니다. 다시 시도하십시오.",
    AccelerationErrorDescription: "가속 실패",
    AccelerationFailedDescription: "가속 오류",
    AccelerationFailedTooltip: "이 뷰에 대해 가속이 설정되지 않았습니다. 가속을 해제하려면 클릭하십시오.",
    AccelerationLearnMore: "자세히 알아보기",
    AccelerationNotUseful: "쿼리를 가속화할 수 없습니다.",
    AccelerationNotUsefulDescription: "쿼리를 가속화할 수 없음",
    AccelerationOffDescription: "가속이 일시 중지됨",
    AccelerationOffTooltip: "이 뷰에 대해 가속이 해제되어 있습니다. 가속을 설정하려면 클릭하십시오.",
    AccelerationOnDescription: "가속 켜짐",
    AccelerationOnTooltip: "이 뷰에 대해 가속이 설정되어 있습니다. 가속을 해제하려면 클릭하십시오.",
    AccelerationPendingDescription: "가속 보류 중",
    AccelerationPendingTooltip: "이 뷰에 대해 가속이 보류 상태입니다. 가속을 해제하려면 클릭하십시오.",
    AccelerationSkippedDuetoResourceConstraintDescription: "가속 리소스 제한을 초과함",
    AccelerationStartsSoonDescription: "보류 중",
    AccelerationToggleSwitchTitle: "가속화 ",
    AccessbilityNotificationButtonDismissLabel: "알림 해제",
    AccessibilityClearSelectionInstructions: "마크 선택을 취소하려면 ESC 키를 누르십시오.",
    AccessibilityDataVisualizationTitleAttr: "데이터 시각화",
    AccessibilityScrollSheetTabsLeft: "왼쪽으로 시트 탭 스크롤",
    AccessibilityScrollSheetTabsRight: "오른쪽으로 시트 탭 스크롤",
    AccessibilityTypeInFieldPrompt: "새 값을 입력한 후 ENTER 키를 눌러 커밋하십시오.",
    AccessibilityViewDataDisabled: "데이터 보기 창에 액세스할 수 있도록 설정되어 있지 않습니다.",
    AccessibilityViewDataInstructions: "데이터 보기 창을 열려면 Enter 키를 누르십시오.",
    AddALayer: "마크|계층 추가",
    AddDataConnection: "데이터 원본 추가",
    AddDataConnectionAdd: "추가",
    AddDataConnectionCancel: "취소",
    AddDataExplanation: "통합 문서에 추가할 게시된 데이터 원본을 선택하십시오.",
    AddDataLearnMore: "자세히 알아보기",
    AddDataLearnToPublish: "Tableau Server에 데이터 원본을 게시하는 방법에 대해 자세히 알아보십시오.",
    AddDataNoPublishedDataSources: "사용할 수 있는 데이터 원본이 없습니다.",
    AddDataNoSearchMatches: "검색어와 일치하는 데이터 원본이 없습니다.",
    AddDataPublishRequirements: "새 데이터 원본을 게시하려면 사용자가 {0}에 대한 게시자여야 합니다.",
    AddDataSearchBrowseSuggestion: "스크롤하여 사용할 수 있는 데이터 원본의 목록을 찾아보십시오.",
    AddDataSearchDifferentTermsSuggestion: "다른 단어로 다시 시도하십시오.",
    AddDataSearchSpellingSuggestion: "맞춤법을 확인하십시오.",
    AddDataSearchSuggestions: "검색 제안:",
    AddDesktopLayout: "데스크톱 레이아웃 추가",
    AddFloatingTextZoneInStoriesLabel: "텍스트를 끌어와서 추가",
    AddPhoneLayout: "스마트폰 레이아웃 추가",
    AddSubscribers: "추가",
    AddSubscribersHeader: "구독자 추가",
    AddTabletLayout: "태블릿 레이아웃 추가",
    AddToLabel: "추가 대상:",
    AggregateCalcWarning: "이 필드에는 집계 계산이 포함되어 있으며, 여기에는 비주얼리제이션 세부 수준에서 의미 있는 데이터만 포함됩니다.",
    AliasDialogHasAliasColumn: "별칭 있음",
    AliasDialogMemberColumn: "멤버",
    AliasDialogValueColumn: "값(별칭)",
    AnalyticsExtensionGenericErrorMsg: "분석 확장 프로그램의 오류로 인해 계속 진행할 수 없습니다.",
    AnalyticsExtensionGenericErrorSubMsg: "다시 연결해 보십시오. 문제가 지속되는 경우 분석 확장 프로그램의 소유자에게 문의하십시오.",
    AnalyticsExtensionGenericTitle: "분석 확장 프로그램 오류",
    AnimationServerRenderingInfoToastMessage: "비주얼리제이션이 복잡해 애니메이션이 일시 중지됩니다. 필터링으로 더 많은 데이터를 제외해 보십시오.",
    April: "4월",
    AprilNarrow: "A",
    AprilShort: "4월",
    AreYouSureDelete: "삭제",
    AskDataAdBubbleTitle: "데이터에 질문 광고 말풍선",
    AskDataAdDialogBody: "사용자가 대시보드를 벗어나지 않고도 데이터에 대해 새로운 질문을 할 수 있습니다.",
    AskDataAdDialogHeader: "데이터에 질문 렌즈 추가",
    AskDataAdDialogTitle: "데이터에 질문 광고 대화록",
    AskDataAdEditDashboardButton: "대시보드 편집",
    AskDataAdLearnMore: "자세히 알아보기",
    AskDataAuthoringPopoverText: "데이터에 질문을 끌어와 대시보드에 추가하십시오.",
    AskDataToolbarButtonLabel: "데이터에 질문",
    August: "8월",
    AugustNarrow: "A",
    AugustShort: "8월",
    AuthAutoSaveWarningDialogCancel: "닫기",
    AuthAutoSaveWarningDialogPublishButton: "지금 게시",
    AuthAutoSaveWarningDialogRevert: "되돌리기",
    AuthAutosaveEnabledToastBody: "변경 내용은 자동으로 비공개 초안에 저장됩니다.",
    AuthAutosaveEnabledToastTitle: "자동 저장이 켜짐",
    AuthAutosaveLearnMore: "자세히 알아보기",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "열",
    AuthCardTitleFilters: "필터",
    AuthCardTitleMarks: "마크",
    AuthCardTitleMeasureValues: "측정값",
    AuthCardTitleMetricsDataFilters: "데이터 필터",
    AuthCardTitlePages: "페이지",
    AuthCardTitleRows: "행",
    AuthCloseEditorButton: "닫기",
    AuthColorEditingDisabled: "여기서 범례를 결합하여 색상을 편집하거나, 각 개별 범례의 색상을 편집합니다.",
    AuthColorPaletteAutomatic: "자동",
    AuthColorPaletteLegacy: "연결 끊김",
    AuthColorPaletteMoreColors: "색상 추가...",
    AuthColorPaletteNone: "없음",
    AuthColorTransparencyLabel: "불투명도",
    AuthConnectToDataSource: "{0}의 데이터 원본에 연결",
    AuthCustomHexColorLabel: "사용자 지정 색상",
    AuthDashboardPaneBlankZone: "빈 페이지",
    AuthDashboardPaneCarouselZone: "회전 슬라이드",
    AuthDashboardPaneExportButtonZone: "다운로드",
    AuthDashboardPaneExtensionZone: "확장 프로그램",
    AuthDashboardPaneFloatingButton: "부동",
    AuthDashboardPaneGridContainer: "그리드",
    AuthDashboardPaneHorizontalStack: "가로",
    AuthDashboardPaneHorizontalZone: "가로",
    AuthDashboardPaneImageZone: "이미지",
    AuthDashboardPaneNavigationButtonZone: "탐색",
    AuthDashboardPaneNewObjects: "새 개체:",
    AuthDashboardPaneSheets: "시트",
    AuthDashboardPaneSize: "크기 - {0}",
    AuthDashboardPaneSizeDefault: "크기",
    AuthDashboardPaneSizeFitAll: "전체 맞춤",
    AuthDashboardPaneSizeFitDefault: "기본값",
    AuthDashboardPaneSizeFitWidth: "너비 맞추기",
    AuthDashboardPaneTextZone: "텍스트",
    AuthDashboardPaneTiledButton: "바둑판식",
    AuthDashboardPaneTitleCheckbox: "대시보드 제목 표시",
    AuthDashboardPaneVerticalStack: "세로",
    AuthDashboardPaneVerticalZone: "세로",
    AuthDashboardPaneWebZone: "웹 페이지",
    AuthDashboardPaneZoneObjects: "개체",
    AuthDraftExistenceUnknownBody: "Tableau에서 기존 초안을 액세스할 수 없거나 지금은 자동 저장을 사용할 수 없습니다. 나중에 다시 시도하거나 마지막으로 게시된 수정 버전으로 되돌릴 수 있습니다.",
    AuthDraftExistenceUnknownHeader: "초안 존재 알 수 없음",
    AuthDraftNotAvailableBody: "Tableau에서 지금 초안을 로드할 수 없습니다. 나중에 다시 시도하거나 마지막으로 게시된 수정 버전으로 되돌릴 수 있습니다.",
    AuthDraftNotAvailableHeader: "초안을 로드할 수 없음",
    AuthDraftNotCurrentDialogEditNewestRevision: "수정 버전 편집",
    AuthDraftNotCurrentDialogMessage: "{1}이(가) 이 통합 문서의 업데이트된 수정 버전을 {0}에 게시했습니다. 초안을 취소하고 현재 수정 버전을 편집하거나, 초안 편집을 다시 시작하시겠습니까?",
    AuthDraftNotCurrentDialogMessage_NoUsername: "이 통합 문서의 업데이트된 수정 버전이 {0}에 게시되었습니다. 초안을 취소하고 현재 수정 버전을 편집하거나, 초안 편집을 다시 시작하시겠습니까?",
    AuthDraftNotCurrentDialogResumeEditingDraft: "내 초안 유지",
    AuthDraftNotCurrentDialogTitle: "최신 초안이 아님",
    AuthFirstPublishInformationToastText: "처음으로 게시한 후에는 초안에 대한 변경 내용이 자동 저장되기 시작합니다.",
    AuthFirstPublishInformationToastTitle: "게시하여 변경 내용 저장",
    AuthFontFamilyAndSize: "{0} {1}",
    AuthFontListLoading: "로드 중…",
    AuthFormatLineVisibilityAutomatic: "자동",
    AuthFormatLineVisibilityOff: "해제",
    AuthFormatLineVisibilityOn: "기준:",
    AuthFormatSectionCollapse: "간단히",
    AuthFormatSectionExpand: "자세히",
    AuthHeatmapIntensityLabel: "강도",
    AuthIncludeTotalsLabel: "총계 포함",
    AuthLabelEditingDisabledDrag: "마크 텍스트를 편집하려면 차원이나 측정값을 텍스트 선반 위에 끌어 놓으십시오.",
    AuthLabelEditingDisabledShow: "마크 레이블을 편집하려면 \"마크 레이블 표시\" 확인란을 선택하십시오.",
    AuthLeftContentPaneLabel: "콘텐츠",
    AuthLeftLayoutPaneLabel: "레이아웃",
    AuthLeftPaneLabelDashboard: "대시보드",
    AuthLeftPaneTabLabelAnalytics: "분석",
    AuthLineAutomaticPreview: "자동",
    AuthLineOffPreview: "해제",
    AuthLineSizePixels: "{0}px",
    AuthMarkSizeLabel: "마크 크기",
    AuthMarksCardChooseField: "기타 필드",
    AuthMarksCardEncodingTooltipBasic: "차원 또는 측정값을 여기로 끌어옵니다.",
    AuthMarksCardEncodingTooltipOptions: "여기로 차원 또는 측정값을 끌어오거나 클릭하여 추가 옵션을 표시합니다.",
    AuthMastheadDone_Confirm_CanLogin: "통합 문서에 변경 내용을 저장하시겠습니까? <br><br>변경 내용 저장을 완료하려면 로그인해야 합니다.",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "로그인 및 저장",
    AuthMastheadDone_Confirm_CanLogin_Confirm_Publish: "로그인 및 게시",
    AuthMastheadDone_Confirm_CanLogin_Deny: "저장 안 함",
    AuthMastheadDone_Confirm_CanLogin_Deny_Publish: "게시 안 함",
    AuthMastheadDone_Confirm_CanLogin_Publish: "통합 문서에 변경 내용을 게시하시겠습니까? <br><br>변경 내용 게시를 완료하려면 로그인해야 합니다.",
    AuthMastheadDone_Confirm_CanPublish: "통합 문서에 변경 내용을 게시하시겠습니까?",
    AuthMastheadDone_Confirm_CanPublishAs: "새 통합 문서에 변경 내용을 게시하시겠습니까?",
    AuthMastheadDone_Confirm_CanPublishAs_Confirm: "복사본 게시",
    AuthMastheadDone_Confirm_CanPublishAs_Deny: "게시 안 함",
    AuthMastheadDone_Confirm_CanPublish_Confirm: "게시",
    AuthMastheadDone_Confirm_CanPublish_Deny: "게시 안 함",
    AuthMastheadDone_Confirm_CanSave: "통합 문서에 변경 내용을 저장하시겠습니까?",
    AuthMastheadDone_Confirm_CanSaveAs: "새 통합 문서에 변경 내용을 저장하시겠습니까?",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "복사본 저장",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "저장 안 함",
    AuthMastheadDone_Confirm_CanSave_Confirm: "저장",
    AuthMastheadDone_Confirm_CanSave_Deny: "저장 안 함",
    AuthMastheadDone_Confirm_Datasource_Description: "새 데이터 원본에 변경 내용을 저장하시겠습니까?",
    AuthMastheadDone_Confirm_Datasource_Title: "데이터 원본 저장",
    AuthMastheadDone_Confirm_Title: "통합 문서 저장",
    AuthMastheadDone_Confirm_Title_Publish: "통합 문서 게시",
    AuthMastheadHelp: "도움말",
    AuthMastheadHelpSearch: "도움말 검색",
    AuthMastheadLogin: "로그인",
    AuthMastheadLogout: "로그아웃",
    AuthMastheadUserPrefs: "사용자 기본 설정",
    AuthMenuBarAnalysis: "분석",
    AuthMenuBarDashboard: "대시보드",
    AuthMenuBarData: "데이터",
    AuthMenuBarDraftIndicator: "초안",
    AuthMenuBarExit: "닫기",
    AuthMenuBarFile: "파일",
    AuthMenuBarFormat: "서식",
    AuthMenuBarMap: "맵",
    AuthMenuBarPublishButtonMenuAriaLabel: "기타 게시 옵션",
    AuthMenuBarPublishButtonPublish: "게시",
    AuthMenuBarPublishButtonPublishAs: "다른 이름으로 게시...",
    AuthMenuBarStory: "스토리",
    AuthMenuBarWindow: "창",
    AuthMenuBarWorksheet: "워크시트",
    AuthMetricsSaveTitle: "메트릭 저장",
    AuthNumberFormatDecimalLabel: "소수 자릿수",
    AuthNumberFormatSeparatorLabel: "구분 기호 포함",
    AuthNumberFormatTypeAuto: "자동",
    AuthNumberFormatTypeCurrency: "통화",
    AuthNumberFormatTypeLabel: "숫자 유형",
    AuthNumberFormatTypeNumber: "숫자",
    AuthNumberFormatTypePercentage: "백분율",
    AuthNumberFormatTypeScientific: "공학용",
    AuthNumberFormatUnitsBillionsEnglish: "십억(B)",
    AuthNumberFormatUnitsBillionsStandard: "십억(G)",
    AuthNumberFormatUnitsLabel: "단위",
    AuthNumberFormatUnitsMillions: "백만(M)",
    AuthNumberFormatUnitsNone: "없음",
    AuthNumberFormatUnitsThousands: "천(K)",
    AuthOffLabel: "해제",
    AuthOnLabel: "설정",
    AuthPillRemove: "제거",
    AuthPublishButtonPublish: "게시",
    AuthPublishTitle: "통합 문서 게시",
    AuthPublishUploadedFileDialogPublish: "업로드된 파일은 편집 세션에서 사용할 수 있지만 초안에 저장되지 않습니다. 에디터를 닫기 전에 통합 문서를 게시하여 이 파일을 저장하십시오.",
    AuthPublishUploadedFileDialogTitle: "업로드된 파일을 저장하시겠습니까?",
    AuthRenameDataSource: "데이터 원본 이름 바꾸기",
    AuthRenameDatasourceAliasHeader: "데이터 원본 별칭 이름 바꾸기",
    AuthRenameDatasourceError: "해당 이름의 데이터 원본이 이미 있습니다. 다른 이름을 사용하여 다시 시도하십시오.",
    AuthRenameDatasourceInfoMessage: "별칭을 추가해도 원래 데이터 원본에는 영향을 주지 않습니다.",
    AuthRenameField: "필드명 바꾸기",
    AuthRenameObject: "테이블 이름 바꾸기",
    AuthRenameSheet: "시트 이름 바꾸기",
    AuthRenameSheetError: "시트 이름을 새 고유 이름으로 바꾸십시오.",
    AuthResetTooltip: "도구 설명 재설정",
    AuthReverseColorLabel: "반전",
    AuthRevertToPublishedDialogBody: "되돌리면 이 초안에서 변경한 내용이 손실됩니다.",
    AuthRevertToPublishedDialogTitle: "마지막으로 게시된 수정 버전으로 되돌리시겠습니까?",
    AuthSaveButtonCancel: "취소",
    AuthSaveButtonSave: "저장",
    AuthSaveConfirmOverwrite: "{0} 덮어쓰시겠습니까?",
    AuthSaveErrorTitle: "저장하는 동안 오류가 발생했습니다.",
    AuthSaveGoneDialogContentAutosaveOn: "변경 내용은 자동으로 비공개 초안에 저장됩니다. 변경 내용을 다른 사람과 공유할 준비가 되면 게시하십시오.",
    AuthSaveGoneDialogContentExplainPublish: "지정된 위치에 작업을 저장하려면 게시 기능을 사용하십시오.",
    AuthSaveGoneDialogContentNotPublished: "처음 게시한 후 변경 내용이 자동 저장되기 시작합니다. 변경 내용을 다른 사람과 공유할 준비가 되면 게시하십시오.",
    AuthSaveGoneDialogTitleAfter: "자동 저장이 켜짐",
    AuthSaveGoneDialogTitleBefore: "저장된 위치는?",
    AuthSaveLabelEmbedPassword: "데이터 원본에 대한 비밀번호 내장",
    AuthSaveLabelLocation: "위치",
    AuthSaveLabelName: "이름",
    AuthSaveLabelProject: "프로젝트",
    AuthSaveLabelSaveTo: "저장 대상:",
    AuthSaveLabelShowTabs: "탭으로 시트 표시",
    AuthSavePersonalSpaceTitle: "개인 공간",
    AuthSaveTitle: "통합 문서 저장",
    AuthSaveWorkbookAccessCurrent: "(현재)",
    AuthSaveWorkbookAccessEmbed: "내 데이터 원본 자격 증명 내장",
    AuthSaveWorkbookAccessHeaderSimple: "통합 문서 액세스",
    AuthSaveWorkbookAccessRequireCreds: "통합 문서를 보려면 데이터 원본 자격 증명이 필요함",
    AuthSaveWorkbookSavedMessage: "저장된 통합 문서",
    AuthSchemaViewerHeaderData: "데이터",
    AuthSchemaViewerHeaderDimensions: "차원",
    AuthSchemaViewerHeaderFolders: "폴더",
    AuthSchemaViewerHeaderMeaures: "측정값",
    AuthSchemaViewerHeaderParameters: "매개 변수",
    AuthSchemaViewerHeaderSets: "집합",
    AuthSchemaViewerHeaderTables: "테이블",
    AuthSchemaViewerNoSearchMatches: "일치 항목이 없음",
    AuthSchemaViewerSearchPlaceholderText: "검색",
    AuthSchemaViewerSearchToggleButtonLabel: "필드 찾기",
    AuthShowMeApply: "적용",
    AuthShowMeCantApply: "적용할 수 없음",
    AuthShowMeMultipleDimensions: "차원",
    AuthShowMeMultipleMeasures: "측정값",
    AuthShowMeRecommended: "권장",
    AuthShowMeSingleDimension: "차원",
    AuthShowMeSingleMeasure: "측정값",
    AuthSteppedColorLabel: "단계",
    AuthStepsLabel: "단계",
    AuthToolbarAddAllSubtotals: "모든 소계 추가",
    AuthToolbarCellSize: "셀 크기",
    AuthToolbarCellSizeBigger: "크게",
    AuthToolbarCellSizeNarrower: "좁게",
    AuthToolbarCellSizeShorter: "낮게",
    AuthToolbarCellSizeSmaller: "작게",
    AuthToolbarCellSizeTaller: "높게",
    AuthToolbarCellSizeWider: "넓게",
    AuthToolbarCellTypeSquare: "사각형",
    AuthToolbarCellTypeText: "텍스트",
    AuthToolbarDownloadWorkbook: "통합 문서",
    AuthToolbarDownloadWorkbookErrorContent: "이 통합 문서에 저장되지 않은 변경 내용이 있습니다. 변경 내용을 저장한 후 다시 시도하십시오.",
    AuthToolbarDownloadWorkbookErrorTitle: "통합 문서를 다운로드할 수 없음",
    AuthToolbarExport: "다운로드",
    AuthToolbarFont: "글꼴",
    AuthToolbarFontDecrease: "글꼴 크기 줄이기",
    AuthToolbarFontIncrease: "글꼴 크기 늘리기",
    AuthToolbarFormatWorkbook: "통합 문서 서식",
    AuthToolbarMarkHideLabels: "레이블 숨기기",
    AuthToolbarMarkShowLabels: "레이블 표시",
    AuthToolbarMore: "자세히",
    AuthToolbarOpenOnDesktopDisabledForPersonalSpaces: "Desktop에서 편집을 사용하려면 통합 문서를 개인 공간 외부에 저장하십시오.",
    AuthToolbarOpenOnDesktopErrorContent: "이 통합 문서에 저장되지 않은 변경 내용이 있습니다. 변경 내용을 저장하고 다시 시도하십시오.",
    AuthToolbarOpenOnDesktopErrorTitle: "Tableau Desktop에서 열 수 없음",
    AuthToolbarPauseUpdates: "업데이트 일시 중지",
    AuthToolbarRedo: "다시 실행",
    AuthToolbarRemoveAllSubtotals: "모든 소계 제거",
    AuthToolbarResumeUpdates: "업데이트 다시 시작",
    AuthToolbarShare: "공유",
    AuthToolbarShowColumnGrandTotals: "행 총합계 표시",
    AuthToolbarShowMe: "표현 방식",
    AuthToolbarShowRowGrandTotals: "열 총합계 표시",
    AuthToolbarSubscribe: "구독",
    AuthToolbarSwap: "바꾸기",
    AuthToolbarTotals: "총계",
    AuthToolbarUndo: "실행 취소",
    AuthToolbarWorksheet: "워크시트",
    AuthToolbarZoomLevel: "맞춤",
    AuthWorkbookFormatPaneClear: "기본값으로 재설정",
    AuthWorkbookFormatPaneClearOne: "지우기",
    AuthWorkbookFormatPaneClearTooltip: "위 통합 문서 서식을 기본 설정으로 재설정",
    AuthWorkbookFormatPaneCloseTooltip: "서식 패널 닫기",
    AuthWorkbookFormatPaneTitle: "통합 문서 서식",
    AuthWorkbookTooLargeForAutosaveOnLoad: "통합 문서 파일이 너무 커서 변경 내용을 자동 저장할 수 없습니다. 변경 내용을 저장하려면 게시하십시오.",
    AuthWorkbookTooLargeForAutosaveOnLoad_CantPublish: "통합 문서 파일이 너무 커서 변경 내용을 자동 저장할 수 없습니다.",
    AuthenticationRequired: "필요한 인증",
    AuthorBylineText: "이 작성자로 더 보기",
    AuthoringAutoRecoveredSessionMessage: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [저장] 또는 [다른 이름으로 저장]을 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessageNoPublish: "마지막 편집 내용이 복구되었습니다. 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessageNoSave: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [다른 이름으로 저장]을 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessagePublish: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [게시] 또는 [다른 이름으로 게시]를 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessagePublishAsNoPublish: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [다른 이름으로 게시]를 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessagePublishNoPublishAs: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [게시]를 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringAutoRecoveredSessionMessageSaveNoSaveAs: "마지막 편집 내용이 복구되었습니다. 모든 변경 내용을 저장하려면 [파일] > [저장]을 클릭하고, 이전 버전으로 되돌리려면 [파일] > [되돌리기]를 클릭하십시오.",
    AuthoringLinePatternLabelDashed: "파선",
    AuthoringLinePatternLabelDotted: "점선",
    AuthoringLinePatternLabelSolid: "실선",
    AuthoringMenuBarCloseButtonLabel: "닫기",
    AuthoringToastActionMessageGoToWorkbook: "통합 문서로 이동",
    AuthoringToastMessagePublishedWorkbook: "\"{0}\"이(가) 게시됨",
    AuthoringToastMessagePublishedWorkbookToLocation: "\"{0}\"이(가) {1}에 게시되었습니다.",
    AuthoringWorkbookTitle: "{0} | 편집",
    AutoSaveAllChangesSaved: "모든 변경 내용 저장됨",
    AutoSaveEditedAt: "편집 날짜: {0}",
    AutoSaveJustPublished: "방금 게시됨",
    AutoSavePublishedAt: "게시 날짜 {0}",
    AutoSavePublishingInProgress: "게시 중...",
    AutoSaveSavingInProgress: "변경 내용 저장 중...",
    AutomaticDashboardSizeText: "대시보드의 크기는 표시되는 화면에 맞게 조정됩니다.",
    AutosaveAvailableToastBody: "정보: 자동 저장이 다시 작동합니다. 변경 내용이 초안에 저장됩니다. ",
    AutosaveUnavailableToastBody: "경고: 자동 저장이 작동하지 않습니다. 게시를 사용하여 변경 내용을 저장하십시오.",
    AutosaveUnavailableToastBody_CantPublish: "경고: 자동 저장이 작동하지 않습니다.",
    BaseClientAllAxisRanges: "모든 축 범위",
    BaseClientAllChanges: "모든 변경 내용",
    BaseClientAllFilters: "모든 필터",
    BaseClientAllSorts: "모든 정렬",
    BaseClientColumns: "열",
    BaseClientInvalidSheet: "\'{0}\' 시트에 대한 뷰를 표시할 수 없습니다. 시트가 잘못되었습니다.",
    BaseClientRows: "행",
    BaseClientSessionExpiredDialogMessage: "뷰어 세션이 만료되었습니다. 브라우저를 새로 고쳐야 합니다.",
    BaseClientSessionExpiredDialogTitle: "세션 만료됨",
    BigQueryUseLegacySQLLabel: "레거시 SQL 사용",
    BinColumnTableName: "구간차원",
    BrowserErrorProcessing: "브라우저 처리 오류",
    BrowserErrorProcessingMessage: "서버 응답을 처리하는 동안 오류가 발생했습니다.",
    BrowserSecurityWarning: "Internet Explorer를 통한 연결은 안전하지 않습니다. 계속하려면 다른 브라우저로 바꾸거나 IT 관리자에게 문의하십시오.",
    CalcColumnTableName: "계산",
    CalcEditorApply: "적용",
    CalcEditorApplyTooltip: "적용(Ctrl+Enter)",
    CalcEditorApplyTooltipMac: "적용(Cmd+Enter)",
    CalcEditorCalcError: "계산에 오류가 있습니다.",
    CalcEditorCalcOk: "계산이 유효합니다.",
    CalcEditorDependenciesPrefix: "이 계산을 변경하면 다음이 변경됩니다.",
    CalcEditorOkButtonTooltip: "적용하고 닫기",
    Cancel: "취소",
    CancelDialogCancellingStatus: "취소 중...",
    CancelDialogProcessingStatus: "처리 중...",
    CannotSaveDataSourcePersonalSpaceContent: "개인 공간에 데이터 원본을 저장할 수 없습니다. 통합 문서를 다른 위치로 이동하여 데이터 원본을 저장하십시오.",
    CannotSaveDataSourcePersonalSpaceTitle: "데이터 원본을 저장할 수 없음",
    ChromeDropdownButtonTooltip: "기타 옵션",
    ClearAliases: "별칭 지우기",
    ClearAllButtonText: "목록 지우기",
    CloseDataSourceErrorDialogEpilogue: "이들 시트에서 데이터 원본을 더는 사용하지 않음을 확인한 후 다시 시도하십시오.",
    CloseDataSourceErrorDialogMessage: "다음 시트에서 \'{0}\' 데이터 원본을 사용 중이므로 데이터 원본을 닫을 수 없습니다.",
    CloseDataSourceErrorDialogTitle: "데이터 원본을 닫을 수 없음",
    CloudConnectionWaitDialogSubtitle: "몇 분이 걸릴 수 있습니다.",
    CloudConnectionWaitDialogSubtitleFilename: "{0}을(를) 로드하는 중입니다. 몇 분 정도 걸릴 수 있습니다.",
    CloudConnectionWaitDialogTitle: "연결 중...",
    CollapseSchemaPane: "축소",
    CombineTwoAccelerationDisallowedReasons: "1. {0} 2. {1}",
    CommentingToolbarButtonLabel: "댓글",
    ConfirmationButtonConfirm: "예",
    ConfirmationButtonDeny: "아니요",
    ConfirmationTitle: "확인",
    ConnectToCloudFileWindowTitle: "{0}에 연결",
    ConnectToData: "데이터에 연결",
    ConnectToDialogErrorMessage: "오류가 발생했으며 [연결] 대화 상자가 올바르게 로드되지 않았습니다. 대화 상자를 다시 열어 보십시오.",
    ConnectionDialogSubtitleConnect: "기존 데이터 원본을 선택하십시오.",
    ConnectionDialogSubtitleCreateAndConnect: "시각화해야 할 데이터에 연결하십시오.",
    ConnectionDialogSubtitleCreateNewConnection: "새 연결을 추가하여 데이터베이스 간 조인을 만듭니다.",
    ConnectionMissingFileDialogMissingDirectoryText: "디렉터리가 없거나 이동했습니다.<br>{0}<br>다른 파일로 바꾸시겠습니까?",
    ConnectionMissingFileDialogMissingDirectoryTextNoUpload: "디렉터리가 없거나 이동했습니다.<br>{0}<br>",
    ConnectionMissingFileDialogText: "참조된 파일 {0}을(를) 찾을 수 없습니다.<br>다른 파일로 바꾸시겠습니까?",
    ConnectionMissingFileDialogTextNoUpload: "참조된 파일 {0}을(를) 찾을 수 없습니다.<br>",
    ConnectionMissingFileDialogTitle: "파일이 없음",
    ConnectorDetailBackButton: "뒤로",
    CreateAreaAnnotationFromVizContextMenu: "영역 주석 추가...",
    CreateConnectionBadPasswordError: "사용자 이름 또는 비밀번호가 잘못되었습니다.  데이터베이스 이름 및 자격 증명을 확인하고 다시 시도하십시오.",
    CreateConnectionErrorHeader: "{0}에 연결할 수 없음",
    CreateConnectionExcelAndText: "Excel 및 텍스트",
    CreateConnectionFromADSSalesforce: "ADS Salesforce",
    CreateConnectionOnTableauServer: "이 사이트 기반",
    CreateConnectionPublishedDatasources: "게시된 데이터 원본",
    CreateConnectionToAFile: "파일",
    CreateConnectionToDataMarketplace: "데이터 리포지토리(베타)",
    CreateConnectionToDataMarketplaceErrorMessage: "데이터 리포지토리(베타) 데이터 집합 로드 오류",
    CreateConnectionToDatabase: "커넥터",
    CreateMapLayersMenuItem: "백그라운드 레이어...",
    CreateMapOptionsMenuItem: "맵 옵션...",
    CreateMarkAnnotationFromVizContextMenu: "마크 주석 추가...",
    CreatePointAnnotationFromVizContextMenu: "요소 주석 추가...",
    CredentialNotEmbedded: "자격 증명이 내장되지 않음",
    CurrentPagePanelNextPage: "다음 페이지",
    CurrentPagePanelPlayForward: "정방향 재생",
    CurrentPagePanelPlayReverse: "역방향 재생",
    CurrentPagePanelPreviousPage: "이전 페이지",
    CurrentPagePanelShowHistory: "기록 표시",
    CurrentPagePanelStop: "중지",
    CurrentSubscribers: "현재 구독자",
    CustomPaletteGroupUnselectedNote: "사용자 지정 색상표가 선택되었습니다. 다른 색상표를 선택하는 경우 이 뷰에서 해당 사용자 지정 색상표를 다시 선택할 수 없습니다.",
    CustomViewsAddYourOwnCustomView: "사용자 고유의 사용자 지정 뷰 추가",
    CustomViewsCancel: "취소",
    CustomViewsCannotChangeDefault: "기본값을 나열되지 않은 사용자 지정 뷰로 변경할 수 없습니다.",
    CustomViewsChangeDefaultTo: "\"{0}\"(으)로 기본값 변경",
    CustomViewsCurrentDefaultIs: "현재 기본값은 \"{0}\"입니다.",
    CustomViewsDialogTitle: "사용자 지정 뷰",
    CustomViewsDone: "완료",
    CustomViewsManageCustomViews: "사용자 지정 뷰 관리",
    CustomViewsManageHeader: "내 사용자 지정 뷰 보급, 이름 바꾸기 및 삭제",
    CustomViewsMyCustomViews: "내 사용자 지정 뷰",
    CustomViewsNameYourCustomView: "사용자 지정 뷰 이름 지정",
    CustomViewsOriginalName: "원래 이름: \"{0}\"",
    CustomViewsOriginalView: "원본",
    CustomViewsOtherCustomViews: "다른 사용자 지정 뷰",
    CustomViewsRemember: "아이디 저장",
    CustomViewsRememberMyChanges: "내 변경 내용 저장",
    CustomViewsSelectCustomView: "사용자 지정 뷰 선택",
    CustomViewsStartManage: "사용자 지정 뷰 관리",
    CustomViewsUndo: "실행 취소",
    CustomViewsUnlistedCustomView: "나열되지 않은 사용자 지정 뷰",
    DashboardAuthZoneHeightDisplay: "높이 {0}",
    DashboardAuthZoneLeftPositionDisplay: "x {0}",
    DashboardAuthZoneTopPositionDisplay: "y {0}",
    DashboardAuthZoneWidthDisplay: "너비 {0}",
    DashboardAuthoringAutoGenerateLayoutTooltip: "레이아웃을 자동 생성하려면 클릭",
    DashboardAuthoringCustomSizeName: "사용자 지정",
    DashboardAuthoringCustomizeLayoutTooltip: "레이아웃을 편집하려면 클릭",
    DashboardAuthoringDeviceLayoutDefault: "기본값",
    DashboardAuthoringDeviceLayoutDesktop: "데스크톱",
    DashboardAuthoringDeviceLayoutPhone: "전화",
    DashboardAuthoringDeviceLayoutTablet: "태블릿",
    DashboardAuthoringHeightSpinnerLabel: "높이",
    DashboardAuthoringMaximumSizeLabel: "최대값",
    DashboardAuthoringMinimumSizeLabel: "최소값",
    DashboardAuthoringSizePopupTitle: "대시보드 크기",
    DashboardAuthoringSizeRadioAriaLabel: "크기 라디오 버튼 그룹",
    DashboardAuthoringWidthSpinnerLabel: "너비",
    DashboardButtonAccessDenied: "액세스 거부됨",
    DashboardGridSize: "그리드 크기(px)",
    DashboardLayoutClearAll: "모두 지우기",
    DashboardLayoutGroup: "그룹화",
    DashboardLayoutRemoveFromGroup: "그룹에서 제거",
    DashboardLayoutUngroup: "그룹 해제",
    DashboardSizeSupressedExceptionMessage: "픽셀 크기가 수신되지 않았습니다. 문제를 해결하려면 브라우저를 새로 고치거나 나중에 다시 시도하십시오.",
    DashboardSpacingNone: "없음",
    DataAccelerationDisableFailureToast: "이 뷰에 대한 가속을 해제할 수 없습니다.",
    DataAccelerationDisableSuccessToast: "뷰 1개에 대한 가속을 해제했습니다.",
    DataAccelerationEnableFailureToast: "이 뷰에 대한 가속을 설정할 수 없습니다.",
    DataAccelerationEnableSuccessToast: "뷰 1개에 대한 가속을 설정했습니다.",
    DataAccelerationFailureToast_ContainsDisallowedSheets: "이 뷰에 대한 가속이 일시 중단되었습니다. 관리자에게 문의하십시오.",
    DataAccelerationFailureToast_DataFreshnessIntervalTooShort: "데이터 새로 고침 정책이 4시간 미만이므로 이 뷰를 가속화할 수 없습니다. 데이터 새로 고침 정책을 편집하십시오.",
    DataAccelerationFailureToast_DataFreshnessIntervalTooShortWithConfig: "데이터 새로 고침 정책이 {0}시간 미만이므로 이 뷰를 가속화할 수 없습니다. 데이터 새로 고침 정책을 편집하십시오.",
    DataAccelerationFailureToast_MissingCredential: "이 뷰는 자격 증명이 내장되어 있지 않으므로 가속화할 수 없습니다.",
    DataAccelerationFailureToast_SheetLimitReached: "이 사이트에서 가속화할 수 있는 뷰 수 제한에 도달했습니다. 관리자에게 문의하십시오.",
    DataAccelerationFailureToast_UserNoPermission: "관리자만 이 사이트에서 뷰를 가속화할 수 있습니다. 관리자에게 문의하십시오.",
    DataAccelerationFailureToast_WithEncryptedExtracts: "이 뷰는 암호화된 데이터 원본 추출을 사용하므로 가속화할 수 없습니다.",
    DataAccelerationRefreshFailureToast: "뷰를 가속화할 수 없습니다. 다시 시도하십시오.",
    DataAccelerationRefreshSuccessToast: "뷰가 가속화된 데이터 {0}(으)로 새로 고쳐졌습니다.",
    DataAlertAccessErrorMessage: "뷰 \"{0}\"이(가) 변경되었으며 액세스하려는 알림이 더 이상 유효하지 않습니다.",
    DataAlertAccessErrorTitle: "알림 액세스 오류",
    DataAlertAddMeFailureToast: "이 알림의 수신자로 추가할 수 없습니다.",
    DataAlertAddMeInvalidEmailAddressFailureToast: "이 알림의 수신자로 추가할 수 없습니다. 알림을 받으려면 Tableau 계정 설정에 이메일 주소를 추가하십시오.",
    DataAlertAddMeSuccessToast: "\"{0}\"에 추가되었습니다.",
    DataAlertChangeOwnerFailureToast: "이 알림의 소유자를 변경할 수 없습니다.",
    DataAlertChangeOwnerSuccessToast: "알림의 소유자가 변경되었습니다.",
    DataAlertCondition: "조건",
    DataAlertCreateButton: "알림 만들기",
    DataAlertCreateButtonSaving: "저장 중...",
    DataAlertCreateFailure: "알림을 만들지 못했습니다.",
    DataAlertCreateSuccess: "알림을 만들었습니다.",
    DataAlertDatasourceError: "데이터 원본에 연결하는 동안 오류가 발생했기 때문에 알림을 만들 수 없습니다. 데이터 원본 자격 증명을 확인하고 다시 시도하십시오.",
    DataAlertDeleteButtonResumeError: "알림 삭제",
    DataAlertDeleteConfirmation: "\"{0}\" 알림을 영구적으로 삭제하시겠습니까? 이 알림에는 {1}명의 받는 사람이 있습니다.",
    DataAlertDeleteConfirmationToast: "\"{0}\"이(가) 삭제되었습니다.",
    DataAlertDeleteFailureToast: "이 알림을 삭제할 수 없습니다.",
    DataAlertDialogTitle: "알림 만들기",
    DataAlertDialogTitleEditMode: "알림 편집",
    DataAlertDisplayAlertFailureToast: "\"{0}\" 알림을 표시하지 못했습니다.",
    DataAlertEditFailureToast: "이 알림을 편집할 수 없습니다.",
    DataAlertErrorDialogTitle: "알림 편집 오류",
    DataAlertErrorDialogViewChanged: "뷰 \"{0}\"이(가) 변경되었으며 편집하려는 알림이 더 이상 유효하지 않습니다.",
    DataAlertErrorDialogViewChangedWithSubject: "뷰 \"{0}\"이(가) 변경되었으며 알림 \"{1}\"이(가) 더 이상 유효하지 않습니다.",
    DataAlertInitFailure: "알림 만들기 대화 상자를 생성할 수 없습니다.",
    DataAlertInvalidPluralUsers: "{0}명의 사용자에게 알림을 보낼 수 없습니다.",
    DataAlertInvalidUser: "1명의 사용자에게 알림을 보낼 수 없습니다.",
    DataAlertLoadCustomizedViewFailure: "사용자 지정 뷰를 로드할 수 없음",
    DataAlertLoadForEditFailure: "편집할 데이터 알림을 로드할 수 없습니다.",
    DataAlertNoSubjectErrorMessage: "알림 이메일의 제목 입력",
    DataAlertNoUsersMatchSearch: "이 검색과 일치하는 사용자 없음",
    DataAlertNotificationInterval: "조건이 참인 경우 알림 보내기:",
    DataAlertOnConstantThreshold: "\'{0}\'이(가) 다음인 경우 알림 보내기:",
    DataAlertPublicCheckboxLabel: "다른 사용자가 볼 수 있도록 설정",
    DataAlertPublicInfo: "뷰에 대한 액세스 권한이 있는 사용자는 이 알림을 보고 이 알림에 본인을 추가할 수 있습니다.",
    DataAlertRecipientPillNoDownloadPermissions: "{0}은(는) 다운로드할 수 있는 사용 권한이 없습니다.",
    DataAlertRecipientPillNoEmail: "{0}에게는 Tableau에 유효한 이메일 주소가 없습니다.",
    DataAlertRecipientPillNoViewPermissions: "{0}은(는) 볼 수 있는 사용 권한이 없습니다.",
    DataAlertRecipientPillUnlicensed: "{0}은(는) 라이선스가 없는 사용자이며 볼 수 있는 사용 권한이 없습니다.",
    DataAlertRecipientWithNoEmail: "Tableau에 사용자의 이메일 주소가 있어야 사용자를 수신자로 추가할 수 있습니다.",
    DataAlertRecipients: "받는 사람",
    DataAlertRemoveMeFailureToast: "이 알림의 수신자에서 제거할 수 없습니다.",
    DataAlertRemoveMeSuccessToast: "{0}에서 제거되었습니다.",
    DataAlertResumeErrorDialogTitle: "알림 다시 시작 오류",
    DataAlertResumedFailureToast: "데이터 알림을 다시 시작하지 못했습니다.",
    DataAlertResumedSucessfullyToast: "데이터 알림이 다시 시작됨",
    DataAlertShowFailureToast: "이 알림에 액세스할 수 없습니다.",
    DataAlertSubject: "제목",
    DataAlertSubjectTemplate: "데이터 알림 - {0}",
    DataAlertThreshold: "임계값",
    DataAlertThresholdConditionMet: "현재 참인 조건",
    DataAlertThresholdConditionUnmet: "현재 참이 아닌 조건",
    DataAlertThresholdErrorDouble: "값은 숫자여야 합니다.",
    DataAlertThresholdErrorGeneric: "값은 숫자여야 합니다.",
    DataAlertThresholdErrorIntegerInputDouble: "값에 실수를 포함할 수 없음",
    DataAlertThresholdErrorIntegerInputNonNumeric: "값은 정수여야 함",
    DataAlertToolbarButtonLabel: "알림",
    DataAlertUpdateButton: "알림 저장",
    DataAlertUpdateFailure: "알림을 업데이트하지 못했습니다.",
    DataAlertUpdateSuccess: "알림을 업데이트했습니다.",
    DataAlertsRecipientsSearchPlaceholder: "수신자 이름 또는 사용자 이름",
    DataCatalogSevereWarningAction: "데이터 세부 정보 열기",
    DataCatalogSevereWarningCount: "중요 데이터 품질 경고가 이 뷰에 영향을 미칩니다.",
    DataDetailsToolbarButtonLabel: "데이터 세부 정보",
    DataGridCancelButton: "취소",
    DataGridErrorButton: "해제",
    DataGridErrorText: "오류가 발생했습니다.",
    DataGridLoadingText: "데이터를 로드하는 중...",
    DataGridNullKeyword: "null",
    DataGridUndefinedKeyword: "정의되지 않음",
    DataGridUpdateButton: "지금 업데이트",
    DataGridZeroRowsText: "데이터 없음",
    DataInterpreterDataLoss: "데이터 해석기가 일부 데이터를 제거했습니다.",
    DataInterpreterDescription: "데이터 해석기에서 {0} 통합 문서를 지울 수 있습니다.",
    DataInterpreterFinished: "데이터 해석기로 정리됨",
    DataInterpreterLoading: "로드 중...",
    DataInterpreterReady: "데이터 해석기 사용",
    DataInterpreterUndo: "변경 내용을 실행 취소하려면 확인란의 선택을 취소합니다.",
    DataLineageToolbarButtonLabel: "계보",
    DataLiveRefreshFailureToast: "뷰를 새로 고칠 수 없습니다. 다시 시도하십시오.",
    DataLiveRefreshSuccessToast: "뷰가 최신 데이터로 새로 고쳐졌습니다.",
    DataSourceConnectionDriverNotInstalledErrorMessage: "데이터 원본에 연결하는 데 필요한 드라이버가 설치되어 있지 않았습니다. Tableau Server 관리자에게 문의하십시오.",
    DataSourceConnectionErrorMessage: "데이터 원본에 연결하는 동안 오류가 발생했습니다. 데이터 원본이 손상되었거나 유효하지 않을 수 있습니다.",
    DataSourceConnectionErrorTitle: "데이터 원본에 연결할 수 없습니다.",
    DataSourceConnectionErrorTitleText: "데이터 원본 \"{0}\"에 연결하는 동안 문제가 발생했습니다. 데이터 원본을 편집하십시오.",
    DataSourceCreationInProgress: "데이터 원본을 만드는 중",
    DataSourceGenericErrorButtonLabel: "다시 시도",
    DataSourceGenericErrorMsg: "데이터 원본의 오류로 인해 작업을 더 진행할 수 없습니다.",
    DataSourceGenericErrorSubMsg: "다시 연결해 보십시오. 문제가 지속되는 경우 데이터 원본의 연결을 끊고 데이터 원본의 소유자에게 문의하십시오.",
    DataSourceGenericTitle: "데이터 원본 오류",
    DataTabAddConnectionToDatasource: "추가",
    DataTabCloseConnection: "제거",
    DataTabConnectionsHeader: "연결",
    DataTabCreateJoinCalculation: "조인 계산 만들기...",
    DataTabCustomSqlTitle: "사용자 지정 SQL",
    DataTabDataGridButtonTooltip: "데이터 원본 미리 보기",
    DataTabEditConnection: "연결 편집...",
    DataTabEditDialogTitle: "조인",
    DataTabEditJoinAddJoinPlaceholder: "새 조인 절 추가",
    DataTabEditJoinCalculation: "조인 계산 편집...",
    DataTabEditJoinClauseHeaderTitle: "데이터 원본",
    DataTabEditJoinClauseRemoveTooltip: "조인 절 제거",
    DataTabEditJoinDisabledTooltip: "이 연결에는 이 조인 유형을 사용할 수 없습니다.",
    DataTabEditJoinFull: "완전 외부",
    DataTabEditJoinFullTooltip: "두 테이블의 모든 값을 포함합니다. 일치 항목이 없는 멤버는 null로 표시됩니다.",
    DataTabEditJoinInner: "안쪽",
    DataTabEditJoinInnerTooltip: "두 테이블에서 모두 일치하는 값만 포함합니다.",
    DataTabEditJoinLeft: "왼쪽",
    DataTabEditJoinLeftTooltip: "모든 멤버를 왼쪽 테이블에 포함하고 모든 일치 항목을 오른쪽 테이블에 포함합니다. 일치 항목이 없는 멤버는 오른쪽에 null로 표시됩니다.",
    DataTabEditJoinRight: "오른쪽",
    DataTabEditJoinRightTooltip: "모든 멤버를 왼쪽 테이블에 포함하고 모든 일치 항목을 오른쪽 테이블에 포함합니다. 일치 항목이 없는 멤버는 왼쪽에 null로 표시됩니다.",
    DataTabExtractCreationSuccessToast: "추출 만들기가 완료되었습니다.",
    DataTabExtractRefreshSuccessToast: "추출 새로 고침이 완료되었습니다.",
    DataTabFilePropertiesCharset: "문자 집합:",
    DataTabFilePropertiesLocale: "로캘:",
    DataTabFilePropertiesQualifier: "텍스트 한정자:",
    DataTabFilePropertiesSeparator: "필드 구분 기호:",
    DataTabFilterInfoLabel: "필터",
    DataTabInitialSql: "초기 SQL...",
    DataTabJoinOnCalculationCaption: "조인 계산",
    DataTabLiveExtractLabel: "연결",
    DataTabMetadataGridButtonTooltip: "메타데이터 관리",
    DataTabName: "데이터 원본",
    DataTabNewAnalyticsExtensionTableLabel: "새 테이블 확장 프로그램",
    DataTabNewAnalyticsExtensionTableTooltip: "새 테이블 확장 프로그램 추가",
    DataTabNewAnalyticsExtensionTableTooltipDisabledExtract: "추출에서 테이블 확장 프로그램이 지원되지 않음",
    DataTabNewCustomSqlLabel: "새 사용자 지정 SQL",
    DataTabNewCustomSqlTooltip: "새 사용자 지정 SQL 쿼리 만들기",
    DataTabNewUnionLabel: "새 유니온",
    DataTabNewUnionTooltip: "새 유니온 추가",
    DataTabQualifierAutomatic: "자동",
    DataTabQualifierNone: "없음",
    DataTabRelationshipCalculationCaption: "관계 계산",
    DataTabRenameConnection: "이름 바꾸기",
    DataTabRenameConnectionTitle: "연결 이름 바꾸기",
    DataTabSchemaReadOnlyNoneSelected: "선택된 {0}이(가) 없습니다.",
    DataTabSchemaSlowMetadataNoneSelected: "{0} 선택",
    DataTabSearchContains: "포함",
    DataTabSearchCountEntityNoMatch: "일치 항목이 없음",
    DataTabSearchCountEntityResult: "일치 항목이 {0}개 있음",
    DataTabSearchEntityCheckPermissions: "사용 권한 확인",
    DataTabSearchEntityCountLoading: "계산 중...",
    DataTabSearchEntityFetchLoading: "결과를 가져오는 중....",
    DataTabSearchEntityLoadButton: "로드",
    DataTabSearchExact: "정확히 일치",
    DataTabSearchFilter: "검색",
    DataTabSearchStartsWith: "시작 문자",
    DataTabSeparatorComma: "쉼표",
    DataTabSeparatorOther: "기타",
    DataTabSeparatorSemicolon: "세미콜론",
    DataTabSeparatorSpace: "공백",
    DataTabSeparatorTab: "탭",
    DataTabSeparatorVerticalBar: "세로 막대",
    DataTabStoredProceduresHeader: "저장 프로시저",
    DataTabStoredProceduresNotAllowed: "다중 연결 데이터 원본에 대해 저장 프로시저를 사용할 수 없습니다.",
    DataTabStoredProceduresPlaceHolder: "저장 프로시저 이름 입력",
    DataTabStoredProceduresWithParamsNotAvailable: "매개 변수가 포함된 저장 프로시저를 실행할 수 없습니다.",
    DataTabStoredProceduresWithParamsNotAvailableTitle: "실행할 수 없음",
    DataTabUnionApplyLabel: "적용",
    DataTabUnionConnectionNameLabel: "연결: ",
    DataTabUnionDifferentConnectionWarning: "동일한 연결의 데이터만 유니온할 수 있습니다.",
    DataTabUnionDragRegionLabel: "유니온으로 테이블 끌기",
    DataTabUnionDragTables: "여기로 테이블 끌기",
    DataTabUnionInvalidPillTooltip: "이 테이블을 찾을 수도 인식할 수도 없습니다. 테이블을 제거하거나 바꾸십시오.",
    DataTabUnionOKLabel: "확인",
    DataTabUnionTablesLabel: "유니온의 테이블: ",
    DataTabUnionUnsupported: "이 데이터베이스에는 유니온을 사용할 수 없으므로 선택한 첫 번째 테이블만 추가됩니다.",
    DataTabViewDataCancel: "취소",
    DataTabViewDataCanceling: "취소 중...",
    DataTabViewDataDialogTitle: "데이터 보기: {0}",
    DataTabViewDataGetDataButtonTooltip: "데이터 가져오기",
    DataTabViewDataLoadingRows: "행을 로드하는 중...",
    DataTabViewDataProcessingRows: "행 처리 중...",
    DataTabViewDataTooltip: "데이터 보기",
    December: "12월",
    DecemberNarrow: "D",
    DecemberShort: "12월",
    DeleteAnnotationFromVizContextMenu: "주석 삭제",
    DeleteSelectedAnnotationFromVizContextMenu: "선택한 주석 삭제",
    DeleteSheetWithVizInTooltipDialogButton: "워크시트 삭제",
    DeleteSheetWithVizInTooltipDialogMessage: "이 워크시트는 다른 워크시트의 도구 설명에 표시됩니다. 이 워크시트를 삭제하면 해당 도구 설명에서도 제거됩니다.<br><br>삭제하시겠습니까?",
    DeleteSheetWithVizInTooltipDialogTitle: "워크시트 삭제",
    DeleteSheetsWithVizInTooltipDialogButton: "워크시트 삭제",
    DeleteSheetsWithVizInTooltipDialogMessage: "이러한 워크시트 중 일부는 다른 워크시트의 도구 설명에 표시됩니다. 이러한 워크시트를 삭제하면 해당 도구 설명에서도 제거됩니다.<br><br>삭제하시겠습니까?",
    DeleteSheetsWithVizInTooltipDialogTitle: "워크시트 삭제",
    DeviceLayoutDefaultMessagePart1: "모든 기기에서 대시보드의 콘텐츠와 레이아웃은 기본 대시보드와 일치합니다.",
    DeviceLayoutDefaultMessagePart2: "대시보드에서 기기가 검색되는 방식을 변경하려면 \"사용자 지정\"을 클릭하십시오.",
    DeviceLayoutSelectorConfirmPromptDesktopLayoutMessage: "데스크톱 레이아웃으로 전환하시겠습니까?",
    DeviceLayoutSelectorConfirmPromptPhoneLayoutMessage: "스마트폰 레이아웃으로 전환하시겠습니까?",
    DeviceLayoutSelectorConfirmPromptTabletLayoutMessage: "태블릿 레이아웃으로 전환하시겠습니까?",
    DeviceLayoutSelectorConfirmPromptTitle: "기기 레이아웃 변경",
    DeviceLayoutSelectorDesktopLayoutToolbarButtonDescription: "데스크톱 레이아웃의 뷰로 전환",
    DeviceLayoutSelectorDesktopLayoutToolbarButtonLabel: "데스크톱 레이아웃",
    DeviceLayoutSelectorPhoneLayoutToolbarButtonDescription: "스마트폰 레이아웃의 뷰로 전환",
    DeviceLayoutSelectorPhoneLayoutToolbarButtonLabel: "스마트폰 레이아웃",
    DeviceLayoutSelectorTabletLayoutToolbarButtonDescription: "태블릿 레이아웃의 뷰로 전환",
    DeviceLayoutSelectorTabletLayoutToolbarButtonLabel: "태블릿 레이아웃",
    DeviceLayoutTableauMobileApp: "Tableau Mobile 앱",
    DeviceLayoutTableauMobileAppTooltip: "Tableau Mobile을 실행하는 기기의 사용 가능한 화면 크기를 표시하기 위해 미리 보기 프레임을 조정합니다.",
    DeviceModel: "모델",
    DevicePreview: "기기 미리 보기",
    DevicePreviewOffTooltip: "기기 미리 보기 해제",
    DevicePreviewTooltip: "다른 기기에서 이 대시보드 미리 보기",
    DeviceType: "기기 유형",
    DialogButtonCancel: "취소",
    DialogButtonDownload: "다운로드",
    DialogButtonExport: "생성",
    DialogButtonNext: "다음",
    DialogButtonOK: "확인",
    DialogButtonPublishChanges: "게시",
    DialogButtonReset: "원래 필드명으로 재설정",
    DialogNoButtonText: "아니요",
    DialogYesButtonText: "예",
    DisabledDataTabTooltipDetails: "다른 데이터 원본을 선택하거나 다운로드한 후 Tableau Desktop을 사용하여 이 통합 문서를 여십시오.",
    DisabledDataTabTooltipInfo: "현재 데이터 원본을 데이터 원본 페이지에서 볼 수 없습니다.",
    DiscoverToolbarButtonLabel: "관련 뷰",
    DisplayFormatDialogTitle: "서식 표시",
    DownloadAsVersionDialogDownloadButton: "다운로드",
    DownloadAsVersionDialogHelpLink: "자세히 알아보기",
    DownloadAsVersionDialogTitle: "Tableau 통합 문서 다운로드",
    DownloadAsVersionDialogWarning: "통합 문서를 다운로드할 버전을 선택하십시오. 통합 문서를 현재 버전으로 유지하거나 다른 버전을 선택할 수 있습니다. 통합 문서를 이전 버전으로 다운그레이드할 경우 일부 기능이 손실될 수 있습니다.",
    DownloadAsVersionDropdownDefaultLabel: "현재",
    DownloadAsVersionDropdownLabel: "버전",
    DownloadDialogDownloadAsVersionButton: "다른 버전으로 다운로드",
    DownloadDraftErrorTitle: "변경 내용을 게시하시겠습니까?",
    DownloadWorkbookErrorContent: "변경 내용이 적용된 통합 문서를 다운로드하려면 먼저 변경 내용을 이 통합 문서에 게시해야 합니다.",
    DraftSwitchToDataTabFailedDialogCloseButtonMessage: "무시(라이브 연결 유지)",
    DraftSwitchToDataTabFailedDialogMessage: "연결 문제로 인해 데이터 연결이 이제 라이브 연결 상태가 되었습니다. 데이터에서 추출을 만들어야 하는 경우 데이터 원본 탭으로 이동하십시오.",
    DraftSwitchToDataTabFailedDialogNavigateButtonMessage: "데이터 원본으로 이동",
    DraftSwitchToDataTabFailedDialogTitle: "데이터 연결이 라이브 상태임",
    DragAndDropAFileOrUploadFromComputer_Part1: "파일 끌어 놓기",
    DragAndDropAFileOrUploadFromComputer_Part2: "또는",
    DragAndDropAFileOrUploadFromComputer_Part3: "컴퓨터에서 업로드",
    DragAndDropError_Multi: "여러 파일을 업로드할 수 없습니다. 대신 단일 파일을 업로드하여 다시 시도하십시오.",
    DragAndDropError_Title: "파일을 업로드할 수 없음",
    DropFieldHintText: "여기에 필드 놓기",
    EditAnnotationFromVizContextMenu: "주석 편집",
    EditConnectionDialogTitle: "연결 편집",
    EditConnectionInformationDialogText: "There was a problem connecting to the data source \"{0}\".<br>Would you like to edit the connection information?",
    EditConnectionInformationDialogTitle: "연결 편집",
    EditDataExplanation: "편집할 게시된 데이터 원본을 선택하십시오.",
    EditDatasourceLinkDisabledTooltip: "데이터 원본을 볼 수 있는 권한만 있기 때문에 이 데이터 원본을 편집할 수 없습니다.",
    EditDatasourceLinkLabel: "편집",
    EmptyDashboardMessage: "여기에 시트 추가",
    EmptyDashboardSubMessage: "왼쪽 목록에서 끌어 놓거나 두 번 클릭하십시오.",
    EmptyFloatingLayoutFlowMessage: "Shift 키를 눌러 부동 개체를 이 컨테이너에 놓습니다.",
    EmptyImageZoneMessage: "개체 메뉴를 사용하여 이미지를 선택하십시오.",
    EmptyLayer: "빈 계층",
    EmptyLayoutGridMessage: "개체를 이 컨테이너로 끌어오거나 Shift 키를 눌러 개체를 위에 띄웁니다.",
    EmptyLayoutStackMessage: "개체를 이 컨테이너로 끌어오거나 Shift 키를 눌러 개체를 위에 띄웁니다.",
    EmptyTextRegionMessage: "텍스트를 추가하거나 편집하려면 두 번 클릭하십시오.",
    EnterFullscreen: "전체 화면",
    EnterFullscreenDescription: "전체 화면에서 보기",
    ExitFullscreen: "전체 화면 끝내기",
    ExitFullscreenDescription: "전체 화면 끝내기",
    ExpandSchemaPane: "확장",
    ExportCrosstabDialogMessage: "크로스탭을 지금 다운로드할 수 있습니다.",
    ExportCrosstabDialogTitle: "크로스탭 다운로드",
    ExportCrosstabToExeclOnStoryWithJsApiErrorMessage: "Tableau JavaScript API는 내장된 스토리에서 크로스탭을 Excel로 다운로드할 수 있도록 지원하지 않습니다. 크로스탭을 CSV로 다운로드해 보십시오.",
    ExportCrosstabToExeclOnStoryWithJsApiErrorTitle: "크로스탭 다운로드 오류",
    ExportDataDialogMessage: "데이터 파일을 지금 다운로드할 수 있습니다.",
    ExportDataDialogTitle: "데이터 다운로드",
    ExportFileConfirmationDialogMessage: "파일을 지금 다운로드할 수 있습니다.",
    ExportFileConfirmationDialogTitle: "파일 다운로드",
    ExportImageDialogMessage: "이미지를 지금 다운로드할 수 있습니다.",
    ExportImageDialogTitle: "이미지 다운로드",
    ExportPowerPointDialogMessage: "PowerPoint를 지금 다운로드할 수 있습니다.",
    ExportPowerPointDialogTitle: "PowerPoint 다운로드",
    ExtensionBlockedByServer: "서버 관리자가 확장 프로그램({0}, {1})의 실행을 차단하기 위해 이러한 확장 프로그램을 차단 목록에 배치했습니다. 자세한 내용은 서버 관리자에게 문의하십시오.",
    ExtensionBlockedPreRelease: "{1}의 {0} 버전은 시험판 버전의 Tableau 확장 프로그램 API를 사용하고 있습니다. 시험판 버전의 Tableau 확장 프로그램 API를 사용하는 확장 프로그램은 시험판 버전의 Tableau에서만 지원됩니다. 릴리스된 버전의 Tableau에서 작동하는 이 확장 프로그램 버전을 구하려면 확장 프로그램 개발자({2})에게 문의하십시오.",
    ExtensionDeniedByUser: "이 확장 프로그램에는 실행 권한이 없습니다. 권한을 승인하려면 페이지를 새로 고쳐 사용 권한을 재설정하십시오.",
    ExtensionDeniedByUserAuthoring: "이 확장 프로그램에는 실행 권한이 없습니다. 권한을 승인하려면 상황에 맞는 메뉴 [기타 옵션]에서 [사용 권한 재설정]을 선택하십시오.",
    ExtensionDisabledOnNewWorkbook: "{0} 확장 프로그램을 사용하려면 먼저 이 통합 문서를 저장해야 합니다. 통합 문서를 저장하고 다시 시도하십시오.",
    ExtensionNotFoundOnSafelist: "{0} 확장 프로그램(url: {1})은 이 사이트의 허용 목록에 없기 때문에 실행이 허용되지 않습니다. 이 확장 프로그램을 허용 목록에 추가하려면 {2}에게 문의하십시오.",
    ExtensionNotSupportedOnPublic: "확장 프로그램 {0} 버전 {1}은(는) 현재 Tableau Public에서 지원되지 않습니다.",
    ExtensionRequiresAuthorization: "{0}<br><br>{0} 확장 프로그램을 실행하려면 권한 부여가 필요합니다. 권한 부여 페이지를 표시하는 데 다소 시간이 걸릴 수 있습니다. 다시 권한 부여하려면 브라우저에서 페이지를 다시 로드하십시오.",
    ExtensionViolatesSafelistPermission: "{0} 확장 프로그램(url: {1})에는 전체 데이터 액세스 권한이 필요하지만 사이트 설정에서 전체 데이터 액세스 권한이 부여되지 않았습니다. 확장 프로그램에 대한 데이터 액세스 설정을 변경하려면 {2}에게 문의하십시오.",
    ExtensionViolatesSafelistPermissionOnPublic: "{0} 확장 프로그램(URL: {1})에는 전체 데이터 액세스 권한이 필요하지만 사이트 설정에서 전체 데이터 액세스 권한이 부여되지 않았습니다.",
    ExtensionsDisabledOnPublic: "확장 프로그램은 현재 Tableau Public에서 지원되지 않습니다.",
    ExtensionsDisabledOnServer: "이 서버에서는 확장 프로그램이 허용되지 않습니다. 확장 프로그램을 허용하도록 이 설정을 변경하려면 서버 관리자에게 문의하십시오.",
    ExtensionsDisabledOnSite: "이 사이트에서는 확장 프로그램이 허용되지 않습니다. 확장 프로그램을 허용하도록 이 설정을 변경하려면 {0}에게 문의하십시오.",
    ExternalMarkMenu: "내장됨",
    ExtractErrorTitle: "오류",
    ExtractInternalErrorMessage: "내부 오류입니다.",
    February: "2월",
    FebruaryNarrow: "F",
    FebruaryShort: "2월",
    FieldNameLabel: "필드명:",
    FieldNameResetErrorMessage: "\"{0}\"을(를) 기본 ({1}) 이름으로 재설정할 수 없습니다. 해당 이름을 통합 문서의 다른 필드에서 현재 사용하고 있기 때문입니다.",
    FieldNameResetErrorTitle: "필드명을 재설정할 수 없음",
    FieldRenameError: "이름이 \"{0}\"인 필드가 이미 있습니다.",
    FieldRenameErrorDialogTitle: "필드명을 바꿀 수 없음",
    FileSingleUploadTitle: "파일 업로드 중",
    FileUploadAccessError: "편집하기 위해 파일이 열렸거나 잠겼기 때문에 파일에 액세스할 수 없습니다. 파일을 닫고 다시 시도하십시오.",
    FileUploadAccessError_Title: "파일 열 수 없음",
    FileUploadButtonAdd: "추가",
    FileUploadButtonCancel: "취소",
    FileUploadButtonClose: "닫기",
    FileUploadButtonLess: "간단히",
    FileUploadButtonMore: "자세히",
    FileUploadButtonReplaceUpdate: "바꾸기 및 업데이트",
    FileUploadButtonRetry: "다시 시도",
    FileUploadButtonSkipPlural: "파일 건너뛰기 및 업로드 시작",
    FileUploadButtonSkipSingular: "파일 건너뛰기 및 업로드 시작",
    FileUploadConnectionCreationErrorReason: "업로드된 파일에서 연결을 생성할 수 없습니다. 다른 파일을 업로드한 다음 다시 시도하십시오.",
    FileUploadConnectionCreationErrorTitle: "업로드된 파일에 연결할 수 없음",
    FileUploadConnectionCreationMultiErrorTitle: "일부 업로드된 파일에 연결할 수 없음",
    FileUploadDSCreationErrorReason: "업로드된 파일에서 데이터 원본을 생성할 수 없습니다. 다른 파일을 업로드한 다음 다시 시도하십시오.",
    FileUploadDSCreationErrorTitle: "데이터 원본이 만들어지지 않음",
    FileUploadDSErrorTitleMultiFailed: "데이터 원본 오류",
    FileUploadDropToUploadInstructions: "업로드할 항목 끌어놓기",
    FileUploadErrorInfosCompletedHeader: "완료",
    FileUploadErrorInfosFailedHeader: "실패",
    FileUploadErrorTitle: "업로드 실패",
    FileUploadErrorTitleMultiComplete: "업로드 완료: {0}개",
    FileUploadErrorTitleMultiFailed: "업로드 실패: {0}개",
    FileUploadFailureIgnoreAndContinueLabel: "무시하고 계속",
    FileUploadFailureTextPlural: "{0}개 파일 업로드 실패",
    FileUploadFailureTextSingular: "{0} 업로드 실패",
    FileUploadFatalErrorFileExists: "업로드하는 파일의 이름이 현재 사용 중인 파일 이름과 같습니다. 기존 파일을 바꾸고 업데이트하시겠습니까? 아니면 이 파일을 새 이름으로 추가하시겠습니까?",
    FileUploadFatalErrorFileIsEmptySubtitle: "이 파일은 비어 있습니다. 다른 파일을 사용하여 다시 시도하십시오.",
    FileUploadFatalErrorFileIsTooBigSubtitle: "파일이 너무 큽니다. 최대 크기: {0}",
    FileUploadFatalErrorSameFileTitle: "동일한 파일 이름",
    FileUploadFatalErrorTitle: "파일을 업로드할 수 없음",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_a: "{0}을(를) {1}(으)로 바꿀 수 없습니다. 대신 {0}을(를) 업로드하여 다시 시도하십시오.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_an: "{0}을(를) {1}(으)로 바꿀 수 없습니다. 대신 {0}을(를) 업로드하여 다시 시도하십시오.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_a: "{0}을(를) {1}(으)로 바꿀 수 없습니다. 대신 {0}을(를) 업로드하여 다시 시도하십시오.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_an: "{0}을(를) {1}(으)로 바꿀 수 없습니다. 대신 {0}을(를) 업로드하여 다시 시도하십시오.",
    FileUploadFatalErrorUnsupportedFileTypeSubtitle: "이 파일 유형은 현재 웹에서 지원되지 않습니다. 이 유형의 파일을 사용하려면 Tableau Desktop에서 파일에 연결한 다음 서버에 게시하십시오.",
    FileUploadFileTypeAccess: "액세스",
    FileUploadFileTypeExcel: "Excel",
    FileUploadFileTypeExcelFile: "Excel 파일",
    FileUploadFileTypeJson: "JSON 파일",
    FileUploadFileTypeOther: "기타 파일",
    FileUploadFileTypeSpatial: "공간 파일",
    FileUploadFileTypeStatistical: "통계 파일",
    FileUploadFileTypeText: "텍스트 파일",
    FileUploadFinishedTitle: "완료",
    FileUploadPreProcessingTitle: "파일 준비 중",
    FileUploadProcessingTitle: "{0}개 파일 처리 중",
    FileUploadProgressDialogTitle: "파일 업로드 진행률",
    FileUploadProgressIndicator: "{0}{2}/{1}{2} 업로드됨",
    FileUploadServerUnresponsive: "서버에서 응답 없음",
    FileUploadTitle: "{0}개 파일 업로드 중",
    FileUploadUploadErrorReason: "파일이 업로드되지 않았습니다.",
    Filter: "필터",
    FindAllButtonLabel: "모두 찾기",
    FindContains: "포함",
    FindExactMatch: "정확히 일치",
    FindInRangeAll: "(전체)",
    FindInRangeLabel: "찾는 위치:",
    FindLabel: "찾기:",
    FindNextButtonLabel: "다음 찾기",
    FindStartsWith: "시작 문자",
    FindTextPlaceHolder: "검색",
    FirstEnding: "{0}일",
    FloatingZoomToolbarLayerControlTooltip: "맵 계층 제어",
    FormatAnimationsSidePaneTitle: "애니메이션 서식...",
    FormatWorksheetContextMenu: "워크시트 서식...",
    Friday: "금요일",
    FridayNarrow: "F",
    FridayShort: "금",
    FullViewDataCaption: "전체 데이터",
    FunctionTypeAggregate: "집계",
    FunctionTypeAll: "전체",
    FunctionTypeClearTooltip: "지우기",
    FunctionTypeDate: "날짜",
    FunctionTypeLogical: "논리",
    FunctionTypeNumber: "숫자",
    FunctionTypeSearchHint: "검색",
    FunctionTypeSpatial: "공간",
    FunctionTypeString: "문자열",
    FunctionTypeTableCalculation: "테이블 계산",
    FunctionTypeType: "유형",
    FunctionTypeUser: "사용자",
    GlassPaneLoading: "로드 중...",
    GlassPaneSessionExpired: "세션 만료됨",
    GlassPaneUpdating: "업데이트 중...",
    GoToAccountSettings: "계정 설정으로 이동하십시오.",
    GoToSheet: "시트로 이동",
    GotoMyLocationPermissionDeniedError: "사용자의 위치를 사용할 수 있는 사용 권한이 Tableau에 없습니다. 위치 설정을 확인하고 다시 시도하십시오.",
    GotoMyLocationPermissionDeniedUnsecureConnection: "사용자의 위치를 사용할 수 있는 사용 권한이 Tableau에 없습니다. 위치 설정을 확인하고 보안 연결(https)을 사용하고 있는지 확인하십시오.",
    GotoMyLocationPositionUnavailableError: "Tableau에서 사용자의 위치를 찾을 수 없습니다. 인터넷 연결을 확인하고 다시 시도하십시오.",
    GotoMyLocationTimeoutError: "사용자 위치 찾기가 시간 초과되었습니다.",
    GotoMyLocationTooltip: "내 위치로 이동",
    GridDialogTitle: "그리드 옵션",
    GroupColumnTableName: "그룹화",
    GroupDialogGroupButtonLabel: "그룹화",
    GroupDialogHideFindOptions: "옵션 숨기기",
    GroupDialogLargeDomainWarning: "이 열의 도메인 크기가 커서 그룹화 기능을 사용할 수 없습니다.",
    GroupDialogRenameButtonLabel: "이름 바꾸기",
    GroupDialogShowFindOptions: "옵션 표시",
    GroupDialogUngroupButtonLabel: "그룹 해제",
    GroupsLabel: "그룹:",
    HelpMenuItemAllHelpTopics: "설치된 도움말 열기",
    HelpMenuItemContactSupport: "지원",
    HelpMenuItemGetHelpAndSupport: "도움말 및 지원",
    HelpMenuItemWebAuthor: "웹 작성 도움말",
    HelpMenuItemWebAuthor1: "통합 문서를 편집 및 작성할 수 있는 사람",
    HelpMenuItemWebAuthor2: "뷰 편집 및 만들기",
    HelpMenuItemWebAuthor3: "통합 문서 만들기 및 뷰 작성",
    HelpMenuItemWebDataSource: "웹 데이터 원본 도움말",
    HideDetailsLabel: "세부 정보 숨기기",
    Hour: "시간",
    Hours: "{0}시간",
    ImagesLimitMessageInClientRendering: "이 비주얼리제이션에 너무 많은 이미지가 있습니다. 필터링하여 500개 미만의 이미지로 줄이고 다시 시도하십시오.",
    ImagesLimitMessageInServerRendering: "이 비주얼리제이션에 너무 많은 이미지가 있습니다. 필터링하여 30개 미만의 이미지로 줄이고 다시 시도하십시오.",
    IncludeOtherLabel: "\'기타\' 포함",
    January: "1월",
    JanuaryNarrow: "J",
    JanuaryShort: "1월",
    July: "7월",
    JulyNarrow: "J",
    JulyShort: "7월",
    June: "6월",
    JuneNarrow: "J",
    JuneShort: "6월",
    LastPublished: "마지막 게시 날짜",
    LayoutPaneArrangeSectionTitle: "정렬",
    LayoutPaneBackgroundColorTitle: "백그라운드",
    LayoutPaneBorderButtonTitle: "테두리",
    LayoutPaneFloatingCheckbox: "부동",
    LayoutPaneHSizeSpinner: "높이",
    LayoutPaneMarginButtonTitle: "바깥쪽 여백",
    LayoutPanePaddingButtonTitle: "안쪽 여백",
    LayoutPaneSelectedItemTitle: "선택한 항목",
    LayoutPaneSpacingAllSidesEqual: "모든 변이 동일",
    LayoutPaneSpacingBottom: "아래쪽",
    LayoutPaneSpacingLeft: "왼쪽",
    LayoutPaneSpacingRight: "오른쪽",
    LayoutPaneSpacingTop: "위쪽",
    LayoutPaneWSizeSpinner: "너비",
    LayoutPaneXPositionSpinner: "X",
    LayoutPaneYPositionSpinner: "Y",
    LayoutPaneZoneTitleCheckbox: "제목 표시",
    LayoutPaneZoneVisibilityFromFieldCheckbox: "값을 사용하여 표시 유형 제어",
    LayoutToggleOptionCustom: "사용자 지정",
    LayoutToggleOptionDefault: "기본값",
    LayoutTreeSectionTitle: "항목 계층",
    LeftPaneAutoGeneratedPhoneLayoutWarningMsg: "이 스마트폰 레이아웃은 자동으로 생성되었습니다. 웹에서 기기 레이아웃을 편집할 수 없습니다. 편집하려면 Tableau Desktop에서 통합 문서를 여십시오.",
    LeftPaneDSDWarningMsg: "웹에서 기기 레이아웃을 편집할 수 없습니다. 편집하려면 Tableau Desktop에서 통합 문서를 여십시오.",
    LegacyPaletteUnselectedNote: "이 색상표가 중단되었습니다. 다른 색상표를 선택하는 경우 이 뷰에서 해당 사용자 지정 색상표를 다시 선택할 수 없습니다.",
    Legend: "범례",
    LegendPanelHighlightSelectedItems: "선택된 항목 하이라이트",
    LinePatternNone: "없음",
    LineTypeHeading: "라인 유형",
    ListLengthFive: "{0}, {1}, {2}, {3} 및 {4}",
    ListLengthFour: "{0}, {1}, {2} 및 {3}",
    ListLengthSeven: "{0}, {1}, {2}, {3}, {4}, {5} 및 {6}",
    ListLengthSix: "{0}, {1}, {2}, {3}, {4} 및 {5}",
    ListLengthThree: "{0}, {1} 및 {2}",
    ListLengthTwo: "{0} 및 {1}",
    LogOnButton: "로그인하여 계속 진행",
    ManageCustomViewsDisabledExplanation: "관리할 사용자 지정 뷰가 없습니다.",
    ManageSubscriptions: "구독 관리",
    MapFloatingToolbarVizCheckBox: "뷰 툴바 표시",
    MapGeoSearchVizCheckBox: "지도 검색기 표시",
    MapOptionsDialogTitle: "맵 옵션",
    MapOptionsDropDownLabel: "단위:",
    MapOptionsLayerControlCheckbox: "계층 컨트롤 표시",
    MapOptionsUnitAutomatic: "자동",
    MapOptionsUnitMetric: "메트릭",
    MapOptionsUnitUS: "인치",
    MapScaleVizibilityCheckBox: "맵 배율 표시",
    MapVizNavCheckBox: "이동 및 확대/축소 허용",
    MapsSearchViewClearInputTooltip: "검색 지우기",
    MapsSearchViewInitialText: "맵 검색",
    March: "3월",
    MarchNarrow: "M",
    MarchShort: "3월",
    MarkTextOneMark: "{0}개 마크",
    MarksCardDropdownAddZoom: "확대 범위에 추가",
    MarksCardDropdownDisableSelection: "선택 사용 안 함",
    MarksCardDropdownDuplicate: "복제",
    MarksCardDropdownHide: "숨기기",
    MarksCardDropdownMoveDown: "아래로 이동",
    MarksCardDropdownMoveUp: "위로 이동",
    MarksCardDropdownRemove: "제거",
    MarksCardDropdownRename: "이름 바꾸기",
    MarksCardDropdownReplicatePanes: "창 간에 복제",
    MarksTextMultiMark: "{0}개 마크",
    MarksToLabelAllowOverlapLabel: "레이블이 다른 마크와 겹치도록 허용",
    MarksToLabelControlLabel: "레이블 마크",
    MarksToLabelFieldLabel: "필드",
    MarksToLabelLabelEndOfLine: "선 끝점 레이블",
    MarksToLabelLabelMaxValueLabel: "레이블 최대값",
    MarksToLabelLabelMinValueLabel: "레이블 최소값",
    MarksToLabelLabelStartOfLine: "선 시작점 레이블",
    MarksToLabelModeAll: "전체",
    MarksToLabelModeHighlight: "하이라이트됨",
    MarksToLabelModeLineEnds: "라인 끝",
    MarksToLabelModeMostRecent: "가장 최근",
    MarksToLabelModeRange: "최소/최대",
    MarksToLabelModeSelection: "선택됨",
    MarksToLabelOptionsLabel: "옵션",
    MarksToLabelScopeCell: "셀",
    MarksToLabelScopeDefault: "패널",
    MarksToLabelScopeLabel: "범위",
    MarksToLabelScopeMultiMark: "라인/파이 차트",
    MarksToLabelScopePane: "패널",
    MarksToLabelScopeTable: "테이블",
    May: "5월",
    MayNarrow: "M",
    MayShort: "5월",
    MenuBackButton: "뒤로",
    MessageCharacterLimit: "{0}/{1}자",
    MetaDataGrid_ConnectionColor: "연결 색상",
    MetaDataGrid_DataType: "데이터 유형",
    MetaDataGrid_FieldName: "필드명",
    MetaDataGrid_RemoteFieldName: "원격 필드명",
    MetaDataGrid_Table: "테이블",
    MetricsToolbarButtonLabel: "메트릭",
    Minutes: "{0}분",
    MissingValidEmailAddressAlert: "구독하려면 계정에 이메일 주소를 추가하십시오.",
    Monday: "월요일",
    MondayNarrow: "M",
    MondayShort: "월",
    MoreActions: "추가 동작",
    NewDashboardName: "새 대시보드",
    NewDataSource: "새 데이터 원본",
    NewStoryName: "새 스토리",
    NewWorksheetName: "새 워크시트",
    NextExpextedSubscriptionBasedOnExtraxtRefresh: "데이터 추출 새로 고침이 완료될 때 구독을 트리거합니다.",
    NotificationIntervalDaily: "최대 1일 간격",
    NotificationIntervalEveryTime: "가능한 한 자주",
    NotificationIntervalHourly: "최대 1시간 간격",
    NotificationIntervalOnlyOnce: "참인 경우 처음 한 번만",
    NotificationIntervalWeekly: "최대 1주 간격",
    November: "11월",
    NovemberNarrow: "N",
    NovemberShort: "11월",
    NumberEnding: "{0}일",
    NumericBinsBinSizeLabel: "구간차원 크기:",
    NumericBinsCntDLabel: "고유 카운트:",
    NumericBinsDiffLabel: "차이:",
    NumericBinsFieldNameLabel: "새 필드명: ",
    NumericBinsMaxLabel: "최대값:",
    NumericBinsMinLabel: "최소값:",
    NumericBinsRangeOfValuesLabel: "값 범위:",
    OAuthFailureForUnsavedWorkbook: "Einstein Discovery 분석 확장 프로그램을 사용하려면 먼저 이 통합 문서를 저장해야 합니다. 통합 문서를 저장하고 다시 시도하십시오.",
    OAuthMissingPassword: "비밀번호 누락",
    OAuthReauthenticateButton: "로그인",
    OAuthReauthenticateMessage: "연결할 수 없는 경우 Tableau 관리자에게 문의하십시오.",
    OAuthReauthenticateTitle: "다시 로그인해야 합니다.",
    October: "10월",
    OctoberNarrow: "O",
    OctoberShort: "10월",
    OldGroupWarning: "이 그룹은 이전 버전의 Tableau에서 만들어졌기 때문에 계산에 사용할 수 없습니다. ",
    OldGroupWarningLink: "복사본을 만드십시오.",
    OpenInTableauMobile: "Tableau Mobile에서 열기",
    OpenOnDesktopDialogPrimaryActionLabel: "통합 문서 닫기",
    OperatorAbove: "초과",
    OperatorAboveOrEqual: "이상",
    OperatorBelow: "미만",
    OperatorBelowOrEqual: "이하",
    OperatorEqual: "같음",
    PanZoomSelectToolsAppendTooltip: "선택 내용에 추가",
    PanZoomSelectToolsCloseButtonTooltipMobile: "선택 모드 끝내기",
    PanZoomSelectToolsLassoSelectionTooltip: "자유형(D)",
    PanZoomSelectToolsLassoSelectionTooltipMobile: "자유형 선택",
    PanZoomSelectToolsPanTooltip: "이동(F)",
    PanZoomSelectToolsPanTooltipMobile: "이동",
    PanZoomSelectToolsRadialSelectionTooltip: "원형(S)",
    PanZoomSelectToolsRadialSelectionTooltipMobile: "원형 선택",
    PanZoomSelectToolsRectangularSelectionTooltip: "직사각형(A)",
    PanZoomSelectToolsRectangularSelectionTooltipMobile: "직사각형 선택",
    PanZoomSelectToolsZoomAreaTooltip: "영역 확대/축소(Z)",
    PanZoomSelectToolsZoomHomeTooltip: "홈 확대/축소",
    PanZoomSelectToolsZoomInTooltip: "확대(두 번 클릭)",
    PanZoomSelectToolsZoomOutTooltip: "축소(Shift+두 번 클릭)",
    PasteDashboardItemFailureHeader: "대시보드 항목 붙여넣기 실패",
    PasteDashboardItemFailureMessage: "해당 개체를 붙여 넣는 동안 오류가 발생했습니다. 다시 붙여 넣으십시오. 문제가 계속 발생하면 관리자에게 문의하여 추가 지원을 요청하십시오.",
    PdfDialogClearAll: "모두 지우기",
    PdfDialogContentStory: "이 스토리",
    PdfDialogOrientation: "방향",
    PdfDialogPaperSize: "용지 크기",
    PdfDialogScalingLabel: "배율",
    PdfDialogSelectAll: "모두 선택",
    PdfDialogSelectionCounter: "{0}/{1}",
    PdfDialogSelectionCounterLabel: "선택한 시트",
    PdfDialogSheetSelectionLabel: "시트 선택",
    PdfDialogSheetSelector: "시트 선택 도구",
    PdfDialogSheetsFromDashboard: "이 대시보드의 특정 시트",
    PdfDialogSheetsFromWorkbook: "이 통합 문서의 특정 시트",
    PdfDialogThumbnailPageSizeLabel: "페이지 크기",
    PdfExportFitOneHigh: "최대 1페이지 높이",
    PdfExportFitOneWide: "최대 1페이지 너비",
    PdfExportFitTwoHigh: "최대 2페이지 높이",
    PdfExportFitTwoWide: "최대 2페이지 너비",
    PdfExportGeneratingPdf: "PDF 생성 중...",
    PdfExportMessageError: "PDF를 생성하는 동안 오류가 발생했습니다.",
    PdfExportMessageSettings: "서버에서 PDF 설정을 가져오고 있습니다.",
    PdfExportMessageSettingsError: "오류: 서버에서 PDF 설정을 검색할 수 없습니다.",
    PdfExportPageOrientationLandscape: "가로",
    PdfExportPageOrientationPortrait: "세로",
    PdfExportPageOrientationPrinter: "프린터",
    PdfExportPageScaleAuto: "자동",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "Executive",
    PdfExportPageSizeFolio: "Folio",
    PdfExportPageSizeLedger: "Ledger",
    PdfExportPageSizeLegal: "Legal",
    PdfExportPageSizeLetter: "Letter",
    PdfExportPageSizeNote: "Note",
    PdfExportPageSizeQuarto: "Quarto",
    PdfExportPageSizeStatement: "Statement",
    PdfExportPageSizeTabloid: "Tabloid",
    PdfExportPageSizeUnspecified: "지정되지 않음",
    PdfExportTitlePDF: "PDF 다운로드",
    PerformanceRecordingLearnMore: "자세히 알아보기",
    PerformanceRecordingToastFirstLine: "성능 기록이 진행 중입니다.",
    PerformanceRecordingToastSecondLine: "기록을 중지하려면 URL에서 :record_performance=yes를 제거하십시오. ",
    PressBackButtonMessage: "[뒤로] 단추를 사용하여 올바른 뷰로 돌아가십시오.",
    PrintPdfDialogContentRequired: "다운로드할 시트를 하나 이상 선택하십시오.",
    PrintPdfDialogMessage: "PDF를 지금 다운로드할 수 있습니다.",
    PrintPdfDialogTitle: "PDF 다운로드",
    PublicAuthSaveErrorTitle: "통합 문서를 저장할 수 없음",
    QuantitativeColorCenter: "가운데",
    QuantitativeColorDialogTitle: "색상 편집 {0}",
    QuantitativeColorEnableSteps: "단계별 색상",
    QuantitativeColorEnd: "끝",
    QuantitativeColorEndSwatch: "오른쪽 끝 색, 사용자 지정 색 {0}",
    QuantitativeColorFullColorRange: "전체 색상 범위 사용",
    QuantitativeColorHideAdvanced: "고급 숨기기",
    QuantitativeColorIncludeTotals: "총계 포함",
    QuantitativeColorPaletteLabel: "색상표",
    QuantitativeColorReset: "재설정",
    QuantitativeColorReverse: "반전",
    QuantitativeColorShowAdvanced: "고급 표시",
    QuantitativeColorStart: "시작",
    QuantitativeColorStartSwatch: "왼쪽 끝 색, 사용자 지정 색 {0}",
    QuantitativeColorSteps: "단계",
    QuickFilterAll: "(전체)",
    QuickFilterAllValues: "모든 값",
    QuickFilterApply: "적용",
    QuickFilterCancel: "취소",
    QuickFilterClearDisabled: "모든 값 표시",
    QuickFilterClearEnabled: "모든 값을 표시하려면 클릭",
    QuickFilterConditionalsCondition: "조건",
    QuickFilterConditionalsLimit: "제한",
    QuickFilterDomainCascading: "계층의 모든 값",
    QuickFilterDomainCascadingContext: "계층 및 컨텍스트의 모든 값",
    QuickFilterDomainContext: "컨텍스트의 모든 값",
    QuickFilterDomainDatabase: "데이터베이스의 모든 값",
    QuickFilterDomainRelevant: "관련된 값만",
    QuickFilterDomainShowFewerValues: "더 적은 값 표시",
    QuickFilterDomainShowMoreValues: "더 많은 값 표시",
    QuickFilterExclusive: "제외",
    QuickFilterInclusive: "포함",
    QuickFilterMultiSelect: "다중",
    QuickFilterMultipleValues: "(다중 값)",
    QuickFilterNoItems: "항목이 없습니다.",
    QuickFilterNonNullValues: "Null이 아닌 값",
    QuickFilterNone: "(없음)",
    QuickFilterOnlyNullValues: "Null 값만",
    QuickFilterSearch: "검색",
    QuickFilterSearchAddItemCtrlEnter: "항목 추가(Ctrl+Enter)",
    QuickFilterSearchAddItemEnter: "항목 추가(Enter)",
    QuickFilterSearchCancel: "검색 취소",
    QuickFilterSearchClearTooltip: "지우기(Esc)",
    QuickFilterSearchCloseTooltip: "닫기(Esc)",
    QuickFilterSearchDataIsCaseSensitive: "데이터는 대/소문자를 구분합니다.",
    QuickFilterSearchFoundMatches: "일치 항목이 {0}개 있음",
    QuickFilterSearchHint: "검색할 텍스트 입력",
    QuickFilterSearchInvalidDataMemberSingular: "\"{0}\"은(는) 필터의 유효한 멤버가 아닙니다.",
    QuickFilterSearchInvalidDataMembersDialogTitle: "데이터 멤버가 잘못되었습니다.",
    QuickFilterSearchInvalidDataMembersPlural: "다음 값은 필터의 유효한 멤버가 아닙니다.",
    QuickFilterSearchNoMatches: "일치 항목이 없습니다.",
    QuickFilterSearchTooltip: "검색(Enter)",
    QuickFilterShowContextMenu: "상황에 맞는 퀵 필터 메뉴 표시",
    QuickFilterShowLargerRange: "더 큰 범위 표시",
    QuickFilterShowSmallerRange: "더 작은 범위 표시",
    QuickFilterSingleSelect: "단일",
    QuickFilterTitleBarExclusive: "{0}(제외)",
    QuickFilterUnknown: "<unknown>",
    QuickFilterValuesInRange: "범위에 있는 값",
    QuickFilterValuesInRangeOrNull: "범위에 있는 값 또는 Null",
    RedirectToApp: "App Store로 리디렉션하시겠습니까?",
    RefLineEditorInputTitle: "값:",
    RefreshDataLabel: "새로 고침",
    RefreshDataSourceListLabel: "목록 새로 고침",
    RefreshLearnMore: "자세히 알아보기",
    RefreshMoreInfo: "이 뷰에 표시된 데이터를 업데이트하려면 새로 고치십시오. 오랫동안 실행되는 쿼리가 뷰에 있는 경우 가속화된 데이터를 사용하면 뷰의 초기 로드 시간이 줄어듭니다.",
    RefreshOptionsLabel: "데이터 새로 고침 옵션",
    RefreshToAccelerated: "{0}에서 가속화된 데이터로 새로 고침",
    RefreshToAcceleratedLabel: "가속화된 데이터 새로 고침",
    RefreshToAcceleratedPending: "가속화된 데이터 사용",
    RefreshToAcceleratedPendingWarning: "가속화된 데이터가 보류 중입니다.",
    RefreshToAcceleratedWithTimestamp: "가속화된 데이터 {0} 사용",
    RefreshToAccelerated_Pending: "가속화된 데이터로 새로 고침(보류 중)",
    RefreshToAccelerated_Timestamps_NotFound: "가속화된 뷰의 타임스탬프를 찾을 수 없음(오류 코드: {0})",
    RefreshToLiveData: "최신 데이터로 새로 고침(로드 시간이 더 오래 걸림)",
    RefreshToLiveDataDescription: "로드 시간이 오래 걸리는 최신 데이터 사용",
    RefreshToLiveDataLabel: "데이터 새로 고침",
    RefreshToLiveDataRadioButtonLabel: "최신 데이터 사용(로드 시간이 더 오래 걸림)",
    RelDateAnchored_curr_day: "고정 일",
    RelDateAnchored_curr_hour: "고정 시간",
    RelDateAnchored_curr_minute: "고정 분",
    RelDateAnchored_curr_month: "고정 월",
    RelDateAnchored_curr_quarter: "고정 분기",
    RelDateAnchored_curr_second: "고정 초",
    RelDateAnchored_curr_week: "고정 주",
    RelDateAnchored_curr_year: "고정 연도",
    RelDateAnchored_last_day: "어제",
    RelDateAnchored_last_hour: "이전 시간",
    RelDateAnchored_last_minute: "이전 분",
    RelDateAnchored_last_month: "이전 월",
    RelDateAnchored_last_quarter: "이전 분기",
    RelDateAnchored_last_second: "이전 초",
    RelDateAnchored_last_week: "이전 주",
    RelDateAnchored_last_year: "이전 연도",
    RelDateAnchored_lastn_day: "지난 % 일",
    RelDateAnchored_lastn_hour: "지난 % 시간",
    RelDateAnchored_lastn_minute: "지난 % 분",
    RelDateAnchored_lastn_month: "지난 % 개월",
    RelDateAnchored_lastn_quarter: "지난 % 분기",
    RelDateAnchored_lastn_second: "지난 % 초",
    RelDateAnchored_lastn_week: "지난 % 주",
    RelDateAnchored_lastn_year: "지난 % 년",
    RelDateAnchored_next_day: "내일",
    RelDateAnchored_next_hour: "다음 시간",
    RelDateAnchored_next_minute: "다음 분",
    RelDateAnchored_next_month: "다음 월",
    RelDateAnchored_next_quarter: "다음 분기",
    RelDateAnchored_next_second: "다음 초",
    RelDateAnchored_next_week: "다음 주",
    RelDateAnchored_next_year: "다음 연도",
    RelDateAnchored_nextn_day: "다음 % 일",
    RelDateAnchored_nextn_hour: "다음 % 시간",
    RelDateAnchored_nextn_minute: "다음 % 분",
    RelDateAnchored_nextn_month: "다음 % 개월",
    RelDateAnchored_nextn_quarter: "다음 % 분기",
    RelDateAnchored_nextn_second: "다음 % 초",
    RelDateAnchored_nextn_week: "다음 % 주",
    RelDateAnchored_nextn_year: "다음 % 년",
    RelDateAnchored_todate_day: "일 고정",
    RelDateAnchored_todate_hour: "시간 고정",
    RelDateAnchored_todate_minute: "분 고정",
    RelDateAnchored_todate_month: "월 고정",
    RelDateAnchored_todate_quarter: "분기 고정",
    RelDateAnchored_todate_second: "초 고정",
    RelDateAnchored_todate_week: "주 고정",
    RelDateAnchored_todate_year: "연도 고정",
    RelDateFilterDays: "일",
    RelDateFilterHours: "시간",
    RelDateFilterISOQuarters: "ISO 분기",
    RelDateFilterISOWeeks: "ISO 주",
    RelDateFilterISOYears: "ISO 연도",
    RelDateFilterMinutes: "분",
    RelDateFilterMonths: "개월",
    RelDateFilterPreview: "{0} - {1}",
    RelDateFilterQuarters: "분기",
    RelDateFilterWeeks: "주",
    RelDateFilterYears: "년",
    RelDatePickerFiveYears: "5년",
    RelDatePickerFiveYearsAbbrev: "5년",
    RelDatePickerOneDay: "1일",
    RelDatePickerOneDayAbbrev: "1일",
    RelDatePickerOneMonth: "1개월",
    RelDatePickerOneMonthAbbrev: "1개월",
    RelDatePickerOneWeek: "1주",
    RelDatePickerOneWeekAbbrev: "1주",
    RelDatePickerOneYear: "1년",
    RelDatePickerOneYearAbbrev: "1년",
    RelDatePickerThreeMonths: "3개월",
    RelDatePickerThreeMonthsAbbrev: "3개월",
    RelDate_curr_day: "오늘",
    RelDate_curr_hour: "현재 시간",
    RelDate_curr_minute: "현재 분",
    RelDate_curr_month: "이번 달",
    RelDate_curr_quarter: "현재 분기",
    RelDate_curr_second: "현재 초",
    RelDate_curr_week: "이번 주",
    RelDate_curr_year: "이번 연도",
    RelDate_last_day: "어제",
    RelDate_last_hour: "이전 시간",
    RelDate_last_minute: "이전 분",
    RelDate_last_month: "이전 월",
    RelDate_last_quarter: "이전 분기",
    RelDate_last_second: "이전 초",
    RelDate_last_week: "이전 주",
    RelDate_last_year: "이전 연도",
    RelDate_lastn_day: "지난 % 일",
    RelDate_lastn_hour: "지난 % 시간",
    RelDate_lastn_minute: "지난 % 분",
    RelDate_lastn_month: "지난 % 개월",
    RelDate_lastn_quarter: "지난 % 분기",
    RelDate_lastn_second: "지난 % 초",
    RelDate_lastn_week: "지난 % 주",
    RelDate_lastn_year: "지난 % 년",
    RelDate_next_day: "내일",
    RelDate_next_hour: "다음 시간",
    RelDate_next_minute: "다음 분",
    RelDate_next_month: "다음 월",
    RelDate_next_quarter: "다음 분기",
    RelDate_next_second: "다음 초",
    RelDate_next_week: "다음 주",
    RelDate_next_year: "다음 연도",
    RelDate_nextn_day: "다음 % 일",
    RelDate_nextn_hour: "다음 % 시간",
    RelDate_nextn_minute: "다음 % 분",
    RelDate_nextn_month: "다음 % 개월",
    RelDate_nextn_quarter: "다음 % 분기",
    RelDate_nextn_second: "다음 % 초",
    RelDate_nextn_week: "다음 % 주",
    RelDate_nextn_year: "다음 % 년",
    RelDate_todate_day: "일간 누계",
    RelDate_todate_hour: "시간 누계",
    RelDate_todate_minute: "분 누계",
    RelDate_todate_month: "월간 누계",
    RelDate_todate_quarter: "사분기별 누계",
    RelDate_todate_second: "초 누계",
    RelDate_todate_week: "주간 누계",
    RelDate_todate_year: "연간 누계",
    ReplayAnimationActualSpeed: "실제 속도",
    ReplayAnimationDoubleSpeed: "2배 속도",
    ReplayAnimationHalfSpeed: "1/2 속도",
    ReplayAnimationMoreOptions: "재생 속도 옵션",
    RequestAbortedByBrowser: "브라우저에 의해 중단된 요청",
    RequestCountExceededTitle: "요청 횟수가 초과됨",
    RequestCountExceededWarning: "요청 횟수가 할당된 시간에 허용된 수를 초과했습니다.",
    ResourceLimited: "가속화된 뷰 수가 한도에 도달했습니다.",
    RowByColumn: "{0}행 x {1}열",
    RowByColumns: "{0}행 x {1}열",
    RowCountLabel: "개 행",
    RowsByColumn: "{0}행 x {1}열",
    RowsByColumns: "{0}행 x {1}열",
    RunOptimizer: "최적화 프로그램 실행...",
    RuntimeAccessibilityEnclosingDivPressEnterTab: "데이터 시각화를 탐색하려면 Enter 키를 누르고, 다음 개체로 이동하려면 Tab 키를 누르십시오.",
    RuntimeAccessibilityHeaderNodeFocus: "선택을 전환하려면 스페이스바를 누르고, 왼쪽 여백으로 돌아가려면 Esc 키를 누르십시오. 머리글을 탐색하려면 화살표 키를 사용하십시오.",
    RuntimeAccessibilitySceneMarginLocationBottom: "아래쪽",
    RuntimeAccessibilitySceneMarginLocationLeft: "왼쪽",
    RuntimeAccessibilitySceneMarginLocationRight: "오른쪽",
    RuntimeAccessibilitySceneMarginLocationTop: "위쪽",
    RuntimeAccessibilitySceneMarginWithHeadersScreenReaderText: "{0}, {1} 여백입니다. 여백 내부를 탐색하려면 Enter 키를 누르고, {2}(으)로 돌아가려면 Esc 키를 누르십시오. 데이터 시각화 요소를 탐색하려면 화살표 키를 사용하십시오.",
    RuntimeAccessibilitySceneScreenReaderText: "마크입니다. {0}. 데이터 시각화 요소를 탐색하려면 화살표 키를 사용하십시오.",
    RuntimeAccessibilitySheetTypeDashboard: "대시보드",
    RuntimeAccessibilitySheetTypeFlexibleDashboard: "유연한 대시보드",
    RuntimeAccessibilitySheetTypeSheet: "시트",
    RuntimeAccessibilitySheetTypeStory: "스토리",
    Saturday: "토요일",
    SaturdayNarrow: "S",
    SaturdayShort: "토",
    SaveAsFailedMessage: "이 통합 문서를 저장할 수 있는 권한이 없습니다. 도움이 필요한 경우 관리자에게 문의하십시오.",
    SaveIncompleteWorkbookWarning: "이 통합 문서가 게시될 때 일부 뷰가 공유되지 않았습니다. 통합 문서를 저장하면 원본 통합 문서를 덮어쓰며 공유되지 않은 뷰가 손실됩니다. 대신 다른 이름으로 저장을 사용하십시오.",
    SaveNoPublishedSheetsBody: "통합 문서를 저장하려면 게시된 시트가 하나 이상 있어야 합니다.  탭을 마우스 오른쪽 단추로 클릭하여 시트를 게시하십시오.",
    SaveNoPublishedSheetsTitle: "저장할 수 없음",
    ScheduleDailyDescription: "매일 {0}",
    ScheduleEvery30MinutesDescription: "다음 시간 후 매 30분마다(15분 및 45분):",
    ScheduleEveryOneHourAtXMinutesPastDescription: "다음 시간 후 매시 {0}분:",
    ScheduleEveryOneHourDescription: "1시간마다",
    ScheduleEveryXHoursStartingAtYDescription: "{1}부터 매 {0}시간마다",
    ScheduleEveryXMinutesDescription: "매 {0}분마다",
    ScheduleHourlyDescription: "{1}부터 {2}까지 {0}마다",
    ScheduleMonthlyDescription: "매월 {0}일, {1}",
    ScheduleMonthlyDescriptionLast: "매월 마지막 날, {0}",
    ScheduleMonthlyDescriptionSecondToLast: "매월 말일 하루 전, {0}",
    ScheduleWeeklyDescription: "매주 {1}, {0}",
    SchemaSearchFilterCalculation: "계산",
    SchemaSearchFilterComment: "댓글",
    SchemaSearchFilterDimension: "차원",
    SchemaSearchFilterMeasure: "측정값",
    SchemaSearchFilterTitle: "필터링 기준",
    ScratchpadTitle: "스크래치 패드",
    SearchDataSources: "데이터 원본 검색",
    SearchResultsNotShownPlural: "결과 {0}개가 표시되지 않았습니다.",
    SearchResultsNotShownSingular: "결과 1개가 표시되지 않았습니다.",
    SearchResultsNotShownZero: "결과 0개가 표시되지 않았습니다.",
    SecondEnding: "{0}일",
    SecurityBlockedURLActionHeader: "URL 차단됨",
    SecurityBlockedURLActionMessage: "보안상 안전하지 않을 수 있는 URL을 차단했습니다.",
    SecurityWarningURLActionHeader: "보안 경고",
    SecurityWarningURLActionMessage: "이 하이퍼링크는 컴퓨터에서 잠재적으로 유해한 소프트웨어를 실행할 수 있습니다. 이 하이퍼링크에 따라 이동하시겠습니까?",
    SelectDataSource: "데이터 원본 선택",
    SelectDataSourcePublishedDSDoesNotExist: "선택한 데이터 원본이 서버에 없습니다.",
    SelectDataSourcePublishedDSSubError: "다른 데이터 원본을 선택하십시오.",
    SelectLinkLabel: "선택",
    SelectText: "선택",
    SelectedMarksText: "{0}/{1}개 마크",
    September: "9월",
    SeptemberNarrow: "S",
    SeptemberShort: "9월",
    SerialScheduleDescription: "{0} - {1}",
    SerialScheduleDescriptionSuffix: "순차(느린 순)",
    ServerAdmin: "서버 관리자",
    ServerDataSourceConnectedWorkbooks: "통합 문서",
    ServerDataSourceConnectedWorkbooksTooltip: "데이터 원본에 연결된 통합 문서 수",
    ServerDataSourceConnectionType: "연결 유형",
    ServerDataSourceConnectsTo: "연결 대상",
    ServerDataSourceConnectsToSeveral: "{0} + {1}",
    ServerDataSourceExtract: "추출",
    ServerDataSourceLive: "라이브",
    ServerDataSourceLiveOrLastExtract: "라이브 / 마지막 추출",
    ServerDataSourceName: "이름",
    ServerDataSourceOwner: "소유자",
    ServerDataSourceProject: "프로젝트",
    ServerDataSourceTotalViews: "뷰: 전체",
    ServerErrorGeneral: "서버와 통신하는 동안 오류가 발생했습니다({0}).<br>임시 네트워크 상태일 수 있습니다.  작업을 다시 시도하십시오.<br>이 상태가 계속되는 경우 해당 시스템 관리자에게 문의하십시오.",
    ServerErrorInvalidJSON: "서버와 통신하는 동안 오류가 발생했습니다(잘못된 JSON).",
    ServerErrorRejected: "서버에서 거부한 요청",
    ServerErrorRejectedMessage: "잘못된 형식의 요청으로 인해 서버에서 응답할 수 없습니다.<br>임시 네트워크 상태일 수 있습니다.  작업을 다시 시도하십시오.<br>이 상태가 계속되는 경우 해당 시스템 관리자에게 문의하십시오.",
    ServerErrorTitle: "서버 오류",
    ServerErrorUnexpected: "예기치 않은 서버 오류",
    ServerErrorUnknown: "Tableau에 예기치 않은 서버 오류가 발생했습니다. 다시 시도하거나 Tableau Server 관리자에게 문의하십시오.",
    SessionEndedAlertMessage: "뷰를 재설정하시겠습니까?",
    SessionEndedAlertTitle: "서버가 세션을 끝냄",
    SessionForbiddenActionMsg: "이 동작을 수행할 권한이 없습니다.",
    SessionForbiddenActionTitle: "금지된 동작",
    SessionInactivityWarning: "다시 방문해 주셔서 감사합니다. 콘텐츠를 다시 로드하는 중입니다.",
    SessionRecoveryWarning: "마지막 몇 가지 변경 내용이 손실되었을 수 있습니다. 변경 내용이 유지되었는지 확인하십시오.",
    SessionUnknownErrorTitle: "알 수 없는 서버 오류",
    SetControlIncludeAllDisabled: "모든 집합 값이 포함됨",
    SetControlIncludeAllEnabled: "모든 집합 값을 포함하려면 클릭",
    ShareDialogAndroidLinkText: "링크를 열려면 아이콘을 누르십시오.",
    ShareDialogDisplayOptions: "표시 옵션",
    ShareDialogDoneButton: "완료",
    ShareDialogEmail: "이메일:",
    ShareDialogEmailHelp: "링크를 복사하여 이메일 메시지로 붙여 넣습니다.",
    ShareDialogEmailLink: "이메일",
    ShareDialogEmbed: "내장:",
    ShareDialogEmbedCodeTableauText: "Tableau 알아보기",
    ShareDialogEmbedHelp: "HTML 코드를 복사하고 붙여 넣어 웹 사이트에 뷰를 포함합니다.",
    ShareDialogEnterUriForBlogEntry: "블로그 항목의 URI를 입력하십시오.",
    ShareDialogEnterValueBetween: "{0}과(와) {1} 사이의 값을 입력하십시오.",
    ShareDialogFacebookLink: "Facebook",
    ShareDialogHeight: "높이:",
    ShareDialogInvalidHeight: "높이가 잘못되었습니다.",
    ShareDialogInvalidWidth: "너비가 잘못되었습니다.",
    ShareDialogLink: "링크:",
    ShareDialogMobileEmailText: "링크를 이메일로 보내려면 아이콘을 누르십시오.",
    ShareDialogMobileLinkText: "다른 공유 옵션에 액세스하려면 아이콘을 길게 누르십시오.",
    ShareDialogPleaseEnterIntegerBetween: "{0}과(와) {1} 사이의 정수를 입력하십시오",
    ShareDialogShowTabs: "탭 표시",
    ShareDialogShowToolbar: "툴바 표시",
    ShareDialogTitle: "뷰 공유",
    ShareDialogTitleForView: "뷰 공유",
    ShareDialogToastError: "오류: ",
    ShareDialogToastSuccess: "성공: ",
    ShareDialogTwitterLink: "트윗",
    ShareDialogUrlForRssLinks: "RSS 링크의 URL:",
    ShareDialogWaitingEmbedMessage: "사용자 지정 내장 코드를 만드는 중...",
    ShareDialogWaitingLinkMessage: "사용자 지정 링크를 만드는 중...",
    ShareDialogWidth: "너비:",
    ShareExplanationDialogTitle: "설명 공유",
    ShareViewOptions: "뷰 공유 옵션",
    SheetReconnectEditConnectionLabel: "연결 편집",
    SheetReconnectEditingNotSupported: "현재 이 데이터 연결은 편집을 지원하지 않습니다.",
    SheetReconnectErrorMessage: "{0}.",
    SheetReconnectLocateFileLabel: "파일 찾기",
    SheetReconnectSignInLabel: "로그인",
    SheetReconnectSubtitle: "\"{0}\" 데이터 원본에 연결하는 동안 문제가 발생했습니다.",
    SheetReconnectTitle: "워크시트 사용 불가능",
    ShowAliases: "별칭 표시",
    ShowDetailsLabel: "세부 정보 표시",
    ShowHiddenFields: "숨겨진 필드 표시",
    SignOutFailedMessage: "로그아웃하지 못했습니다. 다시 시도하십시오.",
    SingleValueFieldCaptionNone: "없음",
    SiteAdmin: "사이트 관리자",
    SizeLegendTextMarkSwatch: "Abc",
    SnapshotApplicationErrorMessage: "이 뷰에 {0}의 스냅샷을 적용할 수 없습니다.",
    SortAtoZAscending: "오름차순(A~Z)",
    SortAtoZAscendingPerTable: "테이블별 오름차순(A~Z)",
    SortDataSourceOrder: "데이터 원본 순서",
    SortFields: "필드 정렬",
    SortModified: "수정됨",
    SortZtoADescending: "내림차순(Z~A)",
    SortZtoADescendingPerTable: "테이블별 내림차순(Z~A)",
    SpecialAll: "전체",
    SpecialError: "#Error",
    SpecialManyValues: "*",
    SpecialMissing: "#Missing",
    SpecialNoAccess: "#NoAccess",
    SpecialRagged: "#Ragged",
    SpecialSkipped: "#Skipped",
    SpecialValuesHeading: "특수 값(예: NULL)",
    SpecialValuesMarkLabel: "마크",
    SpecialValuesMarksHideBreakLines: "숨기기(라인 끊기)",
    SpecialValuesMarksHideConnectLines: "숨기기(라인 연결)",
    SpecialValuesMarksShowAtDefaultValue: "기본값에 표시",
    SpecialValuesMarksShowAtIndicator: "표시기에 표시",
    SpecialValuesTextLabel: "텍스트",
    SpecialValuesTextPlaceholder: "(비어 있음)",
    SpecialWildcard: "와일드카드",
    SpecificExtensionDisabledOnSite: "{0}이(가) 이 사이트에서 해제되어 있습니다. 자세한 내용은 Tableau 관리자에게 문의하십시오.",
    StopUsingAsLinkingField: "{0}을(를) 연결 필드로 사용 중지",
    StoryContentPaneBlankButton: "빈 페이지",
    StoryContentPaneDuplicateButton: "복제",
    StoryContentPaneSaveAsNewPointButton: "새 이름으로 저장",
    StoryContentPaneTitle: "스토리",
    StoryContentShowCaptions: "캡션 표시",
    StoryContentShowTitles: "제목 표시",
    StoryEmptyCaptionText: "캡션 추가",
    StoryEmptyDashboardStoryPointSubtitle: "대시보드에 워크시트를 추가합니다.",
    StoryEmptyDashboardStoryPointTitle: "이 대시보드는 비어 있습니다.",
    StoryEmptyFlipboardSubtitle: "여기에 시트를 추가하려면",
    StoryEmptyFlipboardSubtitleBE: "왼쪽에 있는 목록에서 끌어 놓거나 두 번 클릭하십시오.",
    StoryEmptyFlipboardTitle: "왼쪽의 목록에서 두 번 클릭하십시오.",
    StoryEmptyFlipboardTitleBE: "여기에 시트 추가",
    StoryEmptyWorksheetStoryPointSubtitle: "워크시트에서 비주얼리제이션을 만듭니다.",
    StoryEmptyWorksheetStoryPointTitle: "이 워크시트는 비어 있습니다.",
    StoryNavigatorStyle: "탐색기 스타일",
    StoryNavigatorTypeArrowOnly: "화살표만",
    StoryNavigatorTypeCaption: "캡션 상자",
    StoryNavigatorTypeDot: "점",
    StoryNavigatorTypeNumber: "숫자",
    StoryNavigatorUpdated: "업데이트됨",
    StoryNewPointSectionTitle: "새 스토리 포인트",
    StoryPointDeleteTooltip: "삭제",
    StoryPointNavigatorLocationBottom: "아래쪽",
    StoryPointNavigatorLocationTitle: "탐색기 위치",
    StoryPointNavigatorLocationTop: "위쪽",
    StoryPointNavigatorShowArrows: "화살표 표시",
    StoryPointRevertTooltip: "되돌리기",
    StoryPointSaveAsNewTooltip: "새 스토리 포인트로 저장",
    StoryPointUpdateButton: "업데이트",
    StoryReplaceMessage: "바꾸기",
    SubscribeButtonTooltip: "구독",
    SubscribeCancel: "취소",
    SubscribeContent: "콘텐츠:",
    SubscribeDone: "완료",
    SubscribeEnterAddress: "구독을 받으려면 이메일 주소를 입력하십시오.",
    SubscribeFailure: "구독이 실패했습니다.",
    SubscribeInvalidAddress: "유효한 이메일 주소를 입력하십시오. ",
    SubscribeNext: "다음",
    SubscribeOthers: "구독 신청(다른 사용자)",
    SubscribeOthersFailed: "{0}명의 구독자에 대한 구독을 완료할 수 없습니다.",
    SubscribeOthersSearchPlaceholder: "구독자 이름 또는 사용자 이름",
    SubscribeOthersSuccess: "{0}개의 구독이 생성되었습니다.",
    SubscribeSelf: "구독 신청(본인)",
    SubscribeSelfLabel: "구독하고 싶습니다.",
    SubscribeSheet: "이 시트",
    SubscribeSingleSuccess: "1개의 구독이 생성되었습니다.",
    SubscribeSubject: "제목:",
    SubscribeSubscribe: "구독",
    SubscribeSuccess: "구독이 저장되었습니다.",
    SubscribeTitle: "구독",
    SubscribeTo: "대상:",
    SubscribeViewsToggleLabel: "구독 대상",
    SubscribeWorkbook: "통합 문서의 시트",
    SuggestBinSizeButtonText: "제안",
    SumOf: "합계",
    SummaryViewDataCaption: "요약",
    Sunday: "일요일",
    SundayNarrow: "S",
    SundayShort: "일",
    SupressedExceptionTitle: "이 대시보드를 표시하는 일시적인 문제",
    SwapSheets: "시트 바꾸기",
    TabAuthCategoricalColorEditorAssignPalette: "모양 할당",
    TabAuthCategoricalColorEditorReset: "재설정",
    TabAuthCategoricalColorEditorSelectItem: "데이터 항목 선택",
    TabAuthCategoricalColorEditorSelectPalette: "색상표 선택",
    TabAuthColorEditButton: "색상 편집...",
    TabAuthColorEditLabel: "색상",
    TabAuthColorEditLegendButtonTooltip: "색상 편집...",
    TabAuthColorEditorDialogTitle: "색상 편집 [{0}]",
    TabAuthEditLabelButton: "레이블 편집...",
    TabAuthEditTextButton: "텍스트 편집...",
    TabAuthMarksColorBorderLabel: "테두리",
    TabAuthMarksColorHaloLabel: "후광",
    TabAuthSaveDatasourceConfirmMsg: "데이터 원본 \"{0}\"을(를) 서버에서 공유하여 사용하도록 저장하시겠습니까?",
    TabAuthSaveDatasourceDialogTitle: "데이터 원본 저장",
    TabAuthSaveDatasourceErrorDialogTitle: "데이터 원본 저장 오류",
    TabAuthSaveDatasourceNotReplacedSuccessMessage: "데이터 원본 \"{0}\"이(가) 저장되었지만 이 통합 문서의 연결을 바꾸는 동안 문제가 발생했습니다.",
    TabAuthSaveDatasourceNotReplacedSuccessTitle: "데이터 원본 저장 성공",
    TabAuthSaveDatasourceOverwriteCheckboxLabel: "게시된 기존 데이터 원본 바꾸기",
    TabAuthSaveDatasourceReplaceCheckboxLabel: "저장된 데이터 원본에 연결하도록 통합 문서 업데이트",
    TabAuthSaveDatasourceReplacedSuccessMessage: "데이터 원본이 저장되었습니다.",
    TabAuthSaveDatasourceReplacedSuccessTitle: "데이터 원본 저장 성공",
    TabAuthSaveDatasourceSuccessDialogTitle: "데이터 원본 저장 성공",
    TabAuthSaveDatasourceSuccessMessage: "데이터 원본이 저장되었습니다. 프로젝트 설정에 따라 이 데이터 원본의 \"연결\" 및 기타 사용 권한이 결정됩니다. 데이터 원본 페이지로 이동하여 이 데이터 원본과 해당 속성을 확인할 수 있습니다.",
    TableCalcAddSecondary: "보조 계산 추가",
    TableCalcAtTheLevel: "계산 수준",
    TableCalcComputeCompoundedRate: "혼합 비율 계산",
    TableCalcComputeTotalAcrossPages: "모든 페이지에서 총계 계산",
    TableCalcComputeUsing: "다음을 사용하여 계산",
    TableCalcDialogTitle: "테이블 계산",
    TableCalcInvalidRestartEveryField: "<invalid>",
    TableCalcMissingSortField: "<missing>",
    TableCalcNestedCalculations: "중첩된 계산",
    TableCalcPrimaryTitle: "주 계산 유형",
    TableCalcRelativeTo: "기준",
    TableCalcRestartingEvery: "다시 시작 간격",
    TableCalcSecondaryTitle: "보조 계산 유형",
    TableCalcShowCalculationAssistance: "계산 지원 기능 표시",
    TableCalcSingleTitle: "계산 유형",
    TableCalcSortAscending: "오름차순",
    TableCalcSortAutomatic: "특정 차원",
    TableCalcSortCustom: "사용자 지정",
    TableCalcSortDescending: "내림차순",
    TableCalcSortOrder: "정렬 순서",
    TableCalcSpecificDimensions: "특정 차원",
    TableCalcVisualStructure: "시각적 구조",
    TableCalcWindowCurrentValue: "현재 값",
    TableCalcWindowNullSetting: "값이 부족한 경우 Null",
    TableauMobileWebBannerLabel: "Tableau",
    TableauPublic: "Tableau Public",
    ThirdEnding: "{0}일",
    Thursday: "목요일",
    ThursdayNarrow: "T",
    ThursdayShort: "목",
    TimeLimitExceededTitle: "세션 시간 제한 초과됨",
    TimeLimitExceededWarning: "현재 비주얼리제이션 계산 작업이 세션 시간 제한을 초과했습니다.",
    ToolbarAboutTableau: "Tableau 정보",
    ToolbarBrowserNotSupportedDownloadExplanation: "이 브라우저에서 다운로드가 지원되지 않습니다. 다른 브라우저를 사용하여 다시 시도하십시오.",
    ToolbarConnectToDataSource: "새 데이터 원본 추가",
    ToolbarCurrentView: "현재 뷰",
    ToolbarCustomViewsButtonDescription: "내 사용자 지정을 저장하거나 다른 사용자 지정 뷰 보기",
    ToolbarCustomViewsDefault: "{0}(기본값)",
    ToolbarCustomViewsDeleteButtonTooltip: "이 뷰 삭제",
    ToolbarCustomViewsEmptyPlaceholder: "아직 저장된 항목 없음",
    ToolbarCustomViewsEnterManageButtonText: "관리",
    ToolbarCustomViewsErrorChangingPublicPrivateState: "사용자 지정 뷰의 공개/비공개 상태를 업데이트하는 동안 오류가 발생했습니다.",
    ToolbarCustomViewsErrorDeleting: "사용자 지정 뷰를 삭제하는 동안 오류가 발생했습니다.",
    ToolbarCustomViewsErrorInvalidName: "유효한 사용자 지정 뷰 이름을 입력하십시오.",
    ToolbarCustomViewsErrorRenaming: "사용자 지정 뷰 이름을 바꾸는 동안 오류가 발생했습니다.",
    ToolbarCustomViewsErrorSavingView: "사용자 지정 뷰를 저장하는 동안 오류가 발생했습니다.",
    ToolbarCustomViewsErrorSettingDefault: "기본 사용자 지정 뷰를 설정하는 동안 오류가 발생했습니다.",
    ToolbarCustomViewsExitManageButtonText: "완료",
    ToolbarCustomViewsHideViewButtonTooltipWhenPrivate: "이 뷰는 비공개 뷰입니다.",
    ToolbarCustomViewsHideViewButtonTooltipWhenPublic: "이 뷰는 공개 뷰입니다.",
    ToolbarCustomViewsMakeItMyDefault: "내 기본값으로 설정",
    ToolbarCustomViewsMyViews: "내 뷰",
    ToolbarCustomViewsOriginalView: "원본",
    ToolbarCustomViewsOtherViews: "기타 뷰",
    ToolbarCustomViewsRenameButtonTooltip: "이 뷰의 이름 바꾸기",
    ToolbarCustomViewsRenameUIClearButtonTooltip: "취소",
    ToolbarCustomViewsRenameUIPlaceholderText: "이 뷰의 이름 바꾸기",
    ToolbarCustomViewsSave: "저장",
    ToolbarCustomViewsSaveAreaFillerTextManage: "관리",
    ToolbarCustomViewsSaveAreaFillerTextSelect: "사용자 지정 뷰 선택",
    ToolbarCustomViewsSaveButtonDisabledTitle: "텍스트 필드에 사용자 지정 뷰의 이름을 입력하십시오.",
    ToolbarCustomViewsSetDefaultButtonTooltip: "이 뷰를 기본 뷰로 설정",
    ToolbarCustomViewsSetDefaultButtonTooltipWhenCurrent: "이는 현재 기본값입니다.",
    ToolbarCustomViewsShareItWithOthers: "공용으로 만들기",
    ToolbarCustomViewsSharedView: "공유",
    ToolbarCustomViewsTemplate: "보기: {0}",
    ToolbarCustomViewsViewNamePlaceholder: "이 뷰의 이름 지정",
    ToolbarDisabledCrosstabDownloadExplanation: "크로스탭을 다운로드할 수 없습니다.",
    ToolbarDisabledDataDownloadExplanation: "데이터를 다운로드할 수 없습니다.",
    ToolbarDisabledDownloadExplanation: "데이터 및 크로스탭 다운로드를 사용하도록 설정할 뷰 클릭",
    ToolbarDisabledPdfImageDownloadExplanation: "이미지 또는 PDF를 다운로드하려면 사용 권한이 필요합니다.",
    ToolbarDisabledPdfPptImageDownloadExplanation: "이미지/PDF 다운로드 사용 권한이 필요합니다.",
    ToolbarDisabledWorkbookDownloadExplanation: "통합 문서를 다운로드하려면 사용 권한이 필요합니다.",
    ToolbarDownload: "다운로드",
    ToolbarDownloadSelectFormat: "파일 형식을 선택하십시오.",
    ToolbarEdit: "편집",
    ToolbarEditViewWithSavingAllowedDescription: "변경 후 변경 내용을 이 뷰에 저장",
    ToolbarEmbedTitle: "내장 코드",
    ToolbarEnterFullscreen: "전체 화면",
    ToolbarExitFullscreen: "전체 화면 끝내기",
    ToolbarExport: "다운로드",
    ToolbarExportCrosstab: "크로스탭",
    ToolbarExportData: "데이터",
    ToolbarExportImage: "이미지",
    ToolbarExportPowerPoint: "PowerPoint",
    ToolbarGoToTableauPublic: "Tableau Public으로 이동",
    ToolbarLearnMoreAboutTableau: "Tableau에 대해 자세히 알아보기",
    ToolbarLearnMoreAboutTableauPublic: "Tableau Public에 대해 자세히 알아보기",
    ToolbarMoreByAuthor: "이 작성자에 대한 자세한 정보",
    ToolbarMoreInfo: "추가 정보",
    ToolbarOriginalView: "원래 뷰",
    ToolbarPauseAutomaticUpdates: "자동 업데이트 일시 중지",
    ToolbarPauseUpdatesToast: "데이터 변경 내용 동기화를 일시 중지했습니다.",
    ToolbarPrintToPdf: "PDF",
    ToolbarPublicAvailablePlatforms: "{0} 및 {1}에 사용할 수 있음",
    ToolbarPublicDownloadLabelMobile: "자세히 알아보기",
    ToolbarPublicDownloadLabelWeb: "앱 가져오기",
    ToolbarPublicExplanationText: "대화형 그래프, 맵, 대시보드 및 앱을 만들고, 웹에서 원하는 위치에 게시하십시오. 누구나 이러한 작업을 무료로 수행할 수 있습니다.",
    ToolbarPublicExplanationTitle: "Tableau Public이란?",
    ToolbarRefreshData: "이 뷰에 대한 데이터 새로 고침",
    ToolbarResumeAutomaticUpdates: "자동 업데이트 다시 시작",
    ToolbarRevertAll: "모두 되돌리기",
    ToolbarSendTitle: "링크",
    ToolbarSetCurrentPage: "현재 페이지 설정",
    ToolbarShare: "공유",
    ToolbarShowPerformanceRecording: "성능",
    ToolbarSubscribeAddGroupsHeader: "그룹의 사용자 추가",
    ToolbarSubscribeAddGroupsLabel: "그룹의 사용자 구독",
    ToolbarSubscribeAddGroupsPlaceholder: "그룹의 사용자 추가",
    ToolbarSubscribeAddUsersHeader: "사용자 추가",
    ToolbarSubscribeAddUsersLabel: "사용자 구독",
    ToolbarSubscribeAddUsersOrGroupsPlaceholder: "입력하여 사용자 또는 그룹을 추가하십시오.",
    ToolbarSubscribeAddUsersOrGroupsSelected: "선택됨",
    ToolbarSubscribeAddUsersPlaceholder: "사용자 추가",
    ToolbarSubscribeAllView: "전체 통합 문서",
    ToolbarSubscribeDataPresentCheckbox: "뷰가 비어 있는 경우 보내지 않음",
    ToolbarSubscribeEmailPlaceholder: "이메일",
    ToolbarSubscribeFormat: "서식",
    ToolbarSubscribeFrequency: "빈도",
    ToolbarSubscribeInclude: "포함",
    ToolbarSubscribeMessageEditorPlaceholder: "사용자 지정 메시지 추가",
    ToolbarSubscribeMessageLabel: "메시지(선택 사항)",
    ToolbarSubscribeMessageLabelOld: "메시지",
    ToolbarSubscribeMessagePlaceholder: "사용자 지정 메시지 추가",
    ToolbarSubscribeMessagePlaceholderOld: "사용자 지정 메시지 추가(선택 사항)",
    ToolbarSubscribeMissingSubject: "제목 없음",
    ToolbarSubscribeOnExtractRefresh: "데이터 새로 고침 시",
    ToolbarSubscribeOnSchedule: "선택된 일정에 따라",
    ToolbarSubscribeSchedule: "일정",
    ToolbarSubscribeSubjectPlaceholder: "제목",
    ToolbarSubscribeSubmitButton: "구독",
    ToolbarSubscribeSubmitDisabledTitle: "가입할 일정, 이메일 주소 및 제목이 유효한지 확인하십시오.",
    ToolbarSubscribeThisView: "이 뷰",
    ToolbarSubscribeToImage: "이미지",
    ToolbarSubscribeToImageAndPdf: "이미지 및 PDF",
    ToolbarSubscribeToPdf: "PDF",
    ToolbarSubscribeUserMissingEmail: "오류: {0} 사용자와 연결된 이메일 주소가 없습니다.",
    ToolbarToggleAutoUpdate: "자동 업데이트 설정/해제",
    ToolbarViewCount: "조회수: {0}",
    ToolbarWorkbook: "Tableau 통합 문서",
    TooltipPanZoomMessage: "두 번 클릭하여 확대/축소/누른 채로 이동",
    TrendLineDialogFactorsSectionLabel: "다음 필드를 요소로 포함:",
    TrendLineDialogModelTypeSectionLabel: "모델 유형",
    TrendLineDialogOptionsSectionLabel: "옵션",
    Tuesday: "화요일",
    TuesdayNarrow: "T",
    TuesdayShort: "화",
    UbertipClearSelection: "선택<br/>지우기",
    UbertipCommand1Mobile: "선택<br/>지우기",
    UbertipCommand7Mobile: "데이터 보기",
    UbertipItemsSelected: "개 항목 선택됨",
    UbertipTooltip_Action_DownMobile: "드릴다운",
    UbertipTooltip_Action_UpMobile: "드릴업",
    UbertipTooltip_ExcludeMobile: "제외",
    UbertipTooltip_GroupMobile: "멤버 그룹화",
    UbertipTooltip_KeepOnlyMobile: "이 항목만 유지",
    UbertipTooltip_SortAscendingMobile: "오름차순 정렬",
    UbertipTooltip_SortDescendingMobile: "내림차순 정렬",
    UbertipTooltip_SplitMobile: "멤버 그룹 해제",
    UbertipTooltip_ViewDataMobile: "데이터 보기",
    UnhandledExceptionMessage: "예기치 않은 오류가 발생했습니다. 이 오류가 계속 발생하면 Tableau Server 관리자에게 문의하십시오.<br>세션 ID: {0}<br>{1}",
    UnhandledExceptionTitle: "예기치 않은 오류",
    Unhide: "숨기기 취소",
    UnpublishedChanges: "게시되지 않은 변경 내용",
    UnusedFilesInSaveWorkbookPublishedMessage: "통합 문서에 사용되지 않은 파일이 있습니다. 이러한 파일을 게시하려면 데이터 원본에 추가하십시오.",
    UnusedFilesInSaveWorkbookSavedMessage: "데이터 원본에 포함되지 않은 텍스트 파일이 있습니다. 이러한 텍스트 파일을 저장하려면 데이터 원본에 추가하십시오.",
    UploadBytes: "바이트",
    UploadGB: "GB",
    UploadKB: "KB",
    UploadMB: "MB",
    UseAsLinkingField: "{0}을(를) 연결 필드로 사용",
    UserHasNoEmailAddressWarning: "사용자의 이메일 주소가 Tableau에 없습니다.",
    ViewCommentsMobileWebBannerLabel: "댓글 보기",
    ViewDataDownloadDataAsFile: "텍스트 파일로 모든 행 다운로드",
    ViewDataH1: "데이터 보기",
    ViewDataNewWindowConfirmationDialogContent: "이 브라우저에서 데이터 보기 창을 차단하고 있습니다. 새 창에서 데이터 보기를 여시겠습니까?",
    ViewDataShowAllColumns: "모든 열 표시",
    ViewDataShowingRows: "처음 {0}개 행이 표시되었습니다.",
    ViewDataSummary: "요약",
    ViewDataUnderlying: "전체 데이터",
    ViewDataWindowModalBlockerDialogContent: "데이터 보기 창이 아직 열려 있습니다. 데이터 보기 창을 닫으시겠습니까?",
    VizObjectTypeReferenceLine: "참조선",
    WaitDialogDefaultTitleStatus: "처리 중...",
    WarningTitle: "경고",
    WebZoneDisabled: "이 사이트에 대해 웹 페이지 개체를 사용할 수 없습니다. 자세한 내용은 Tableau 관리자에게 문의하십시오.",
    WebZoneEmptyURL: "개체 메뉴를 사용하여 웹 사이트 URL을 선택하십시오.",
    WebZoneHttpsEmbedHttpAuthoring: "서버가 HTTPS를 실행하기 때문에 이 웹 페이지 개체의 URL은 http:// 대신 https://를 사용하여 지정해야 합니다.",
    WebZoneHttpsEmbedHttpView: "웹 페이지 개체를 표시할 수 없습니다(URL은 https://로 시작해야 함).",
    WebZoneUrlDialogTitle: "URL 편집",
    Wednesday: "수요일",
    WednesdayNarrow: "W",
    WednesdayShort: "수",
    WindowTableCalcNextValuesLabel: "다음 값",
    WindowTableCalcPreviousValuesLabel: "이전 값",
    WindowTableCalcSummarizeUsing: "다음을 사용하여 값 요약",
    WorkbookAccessWarningBody: "이 통합 문서의 기존 추출 새로 고침, 알림 및 구독이 중지될 수 있습니다.",
    WorkbookAccessWarningHeader: "경고",
    WorkbookOptimizer: "통합 문서 최적화 프로그램",
    WorkbookTemplatesCategoryLabel: "액셀러레이터",
    WorkbookTemplatesExtractErrorBannerActionMessage: "샘플 데이터로 계속 진행",
    WorkbookTemplatesExtractErrorBannerMessage: "대시보드에서 데이터를 로드할 수 없습니다. 자세한 내용은 이메일을 확인하십시오.",
    WorkbookTemplatesPublishErrorBannerActionMessage: "다시 시도",
    WorkbookTemplatesPublishErrorBannerMessage: "통합 문서를 게시할 수 없습니다. 다시 시도하거나 문제가 지속되는 경우 관리자에게 문의하십시오.",
    WorkbookTemplatesSampleData: "데이터 추출 작성 중...",
    WorkbookTemplatesServiceDownMessage: "현재 액셀러레이터를 사용할 수 없습니다. 나중에 다시 시도해주십시오.",
    WorkbookTemplatesSuccessBannerActionMessage: "통합 문서 다시 로드",
    WorkbookTemplatesSuccessBannerMessage: "추출이 완료되었습니다. 탐색을 시작하려면 통합 문서를 다시 로드하십시오.",
    WorkbookTemplatesTypeLabel: "액셀러레이터",
    ZoneListTitle: "레이아웃 - {0}"
  };

  function replaceAll(s, oldValue, newValue) {
    newValue = (newValue === undefined || newValue === null) ? '' : newValue;
    return s.split(oldValue).join(newValue);
  }

  w.tab = w.tab || {};
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k];
              for (var i = 0, len = arguments.length; i < len; i++) {
                formattedString = replaceAll(formattedString, '{' + i + '}', arguments[i]);
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));
